import { g as getPost } from "./cache_CMM7wTu7.mjs";
import * as import__shikijs_engine_oniguruma from "@shikijs/engine-oniguruma";
import { createBundledHighlighter, createSingletonShorthands, guessEmbeddedLanguages } from "@shikijs/core";
//#region node_modules/marked/lib/marked.esm.js
/**
* marked v18.0.11 - a markdown parser
* Copyright (c) 2018-2026, MarkedJS. (MIT License)
* Copyright (c) 2011-2018, Christopher Jeffrey. (MIT License)
* https://github.com/markedjs/marked
*/
/**
* DO NOT EDIT THIS FILE
* The code in this file is generated from files in ./src/
*/
function A() {
	return {
		async: !1,
		breaks: !1,
		extensions: null,
		gfm: !0,
		hooks: null,
		pedantic: !1,
		renderer: null,
		silent: !1,
		tokenizer: null,
		walkTokens: null
	};
}
var R = A();
function j(l) {
	R = l;
}
var z = { exec: () => null };
function I(l) {
	let e = [];
	return (t) => {
		let n = Math.max(0, Math.min(3, t - 1)), s = e[n];
		return s || (s = l(n), e[n] = s), s;
	};
}
function k(l, e = "") {
	let t = typeof l == "string" ? l : l.source, n = {
		replace: (s, r) => {
			let i = typeof r == "string" ? r : r.source;
			return i = i.replace(m.caret, "$1"), t = t.replace(s, i), n;
		},
		getRegex: () => new RegExp(t, e)
	};
	return n;
}
var Oe = ((l = "") => {
	try {
		return !!new RegExp("(?<=1)(?<!1)" + l);
	} catch {
		return !1;
	}
})();
var m = {
	codeRemoveIndent: /^(?: {1,4}| {0,3}\t)/gm,
	outputLinkReplace: /\\([\[\]])/g,
	indentCodeCompensation: /^(\s+)(?:```)/,
	beginningSpace: /^\s+/,
	endingHash: /#$/,
	startingSpaceChar: /^ /,
	endingSpaceChar: / $/,
	nonSpaceChar: /[^ ]/,
	newLineCharGlobal: /\n/g,
	tabCharGlobal: /\t/g,
	multipleSpaceGlobal: /\s+/g,
	blankLine: /^[ \t]*$/,
	doubleBlankLine: /\n[ \t]*\n[ \t]*$/,
	blockquoteStart: /^ {0,3}>/,
	blockquoteSetextReplace: /\n {0,3}((?:=+|-+) *)(?=\n|$)/g,
	blockquoteSetextReplace2: /^ {0,3}>[ \t]?/gm,
	listReplaceNesting: /^ {1,4}(?=( {4})*[^ ])/g,
	listIsTask: /^\[[ xX]\] +\S/,
	listReplaceTask: /^\[[ xX]\] +/,
	listTaskCheckbox: /\[[ xX]\]/,
	anyLine: /\n.*\n/,
	hrefBrackets: /^<(.*)>$/,
	tableDelimiter: /[:|]/,
	tableAlignChars: /^\||\| *$/g,
	tableRowBlankLine: /\n[ \t]*$/,
	tableAlignRight: /^ *-+: *$/,
	tableAlignCenter: /^ *:-+: *$/,
	tableAlignLeft: /^ *:-+ *$/,
	startATag: /^<a /i,
	endATag: /^<\/a>/i,
	startPreScriptTag: /^<(pre|code|kbd|script)(\s|>)/i,
	endPreScriptTag: /^<\/(pre|code|kbd|script)(\s|>)/i,
	startAngleBracket: /^</,
	endAngleBracket: />$/,
	pedanticHrefTitle: /^([^'"]*[^\s])\s+(['"])(.*)\2/,
	unicodeAlphaNumeric: /[\p{L}\p{N}]/u,
	escapeTest: /[&<>"']/,
	escapeReplace: /[&<>"']/g,
	escapeTestNoEncode: /[<>"']|&(?!(#\d{1,7}|#[Xx][a-fA-F0-9]{1,6}|\w+);)/,
	escapeReplaceNoEncode: /[<>"']|&(?!(#\d{1,7}|#[Xx][a-fA-F0-9]{1,6}|\w+);)/g,
	caret: /(^|[^\[])\^/g,
	percentDecode: /%25/g,
	findPipe: /\|/g,
	splitPipe: / \|/,
	slashPipe: /\\\|/g,
	carriageReturn: /\r\n|\r/g,
	spaceLine: /^ +$/gm,
	notSpaceStart: /^\S*/,
	endingNewline: /\n$/,
	listItemRegex: (l) => new RegExp(`^( {0,3}${l})((?:[	 ][^\\n]*)?(?:\\n|$))`),
	nextBulletRegex: I((l) => new RegExp(`^ {0,${l}}(?:[*+-]|\\d{1,9}[.)])((?:[ 	][^\\n]*)?(?:\\n|$))`)),
	hrRegex: I((l) => new RegExp(`^ {0,${l}}((?:- *){3,}|(?:_ *){3,}|(?:\\* *){3,})(?:\\n+|$)`)),
	fencesBeginRegex: I((l) => new RegExp(`^ {0,${l}}(?:\`\`\`|~~~)`)),
	headingBeginRegex: I((l) => new RegExp(`^ {0,${l}}#`)),
	htmlBeginRegex: I((l) => new RegExp(`^ {0,${l}}<(?:[a-z].*>|!--)`, "i")),
	blockquoteBeginRegex: I((l) => new RegExp(`^ {0,${l}}>`))
};
var Te = /^(?:[ \t]*(?:\n|$))+/;
var we = /^((?: {4}| {0,3}\t)[^\n]+(?:\n(?:[ \t]*(?:\n|$))*)?)+/;
var ye = /^ {0,3}(`{3,}(?=[^`\n]*(?:\n|$))|~{3,})([^\n]*)(?:\n|$)(?:|([\s\S]*?)(?:\n|$))(?: {0,3}\1[~`]* *(?=\n|$)|$)/;
var q = /^ {0,3}((?:-[\t ]*){3,}|(?:_[ \t]*){3,}|(?:\*[ \t]*){3,})(?:\n+|$)/;
var Pe = /^ {0,3}(#{1,6})(?=\s|$)(.*)(?:\n+|$)/;
var U = / {0,3}(?:[*+-]|\d{1,9}[.)])/;
var oe = /^(?!bull |blockCode|fences|blockquote|heading|html|table)((?:.|\n(?!\s*?\n|bull |blockCode|fences|blockquote|heading|html|table))+?)\n {0,3}(=+|-+) *(?:\n+|$)/;
var ae = k(oe).replace(/bull/g, U).replace(/blockCode/g, /(?: {4}| {0,3}\t)/).replace(/fences/g, / {0,3}(?:`{3,}|~{3,})/).replace(/blockquote/g, / {0,3}>/).replace(/heading/g, / {0,3}#{1,6}(?:\s|$)/).replace(/html/g, / {0,3}<[^\n>]+>\n/).replace(/\|table/g, "").getRegex();
var Se = k(oe).replace(/bull/g, U).replace(/blockCode/g, /(?: {4}| {0,3}\t)/).replace(/fences/g, / {0,3}(?:`{3,}|~{3,})/).replace(/blockquote/g, / {0,3}>/).replace(/heading/g, / {0,3}#{1,6}(?:\s|$)/).replace(/html/g, / {0,3}<[^\n>]+>\n/).replace(/table/g, / {0,3}\|?(?:[:\- ]*\|)+[\:\- ]*\n/).getRegex();
var K = /^([^\n]+(?:\n(?!hr|heading|lheading|blockquote|fences|list|html|table|[ \t]+\n)[^\n]+)*)/;
var _e = /^[^\n]+/;
var W = /(?!\s*\])(?:\\[\s\S]|[^\[\]\\])+/;
var $e = k(/^ {0,3}\[(label)\]: *(?:\n[ \t]*)?([^<\s][^\s]*|<.*?>)(?:(?: +(?:\n[ \t]*)?| *\n[ \t]*)(title))? *(?:\n+|$)/).replace("label", W).replace("title", /(?:"(?:\\"?|[^"\\])*"|'[^'\n]*(?:\n[^'\n]+)*\n?'|\([^()]*\))/).getRegex();
var Le = k(/^(bull)([ \t][^\n]*?)?(?:\n|$)/).replace(/bull/g, U).getRegex();
var Q = "address|article|aside|base|basefont|blockquote|body|caption|center|col|colgroup|dd|details|dialog|dir|div|dl|dt|fieldset|figcaption|figure|footer|form|frame|frameset|h[1-6]|head|header|hr|html|iframe|legend|li|link|main|menu|menuitem|meta|nav|noframes|ol|optgroup|option|p|param|search|section|summary|table|tbody|td|tfoot|th|thead|title|tr|track|ul";
var X = /<!--(?:-?>|[\s\S]*?(?:-->|$))/;
var Ee = k("^ {0,3}(?:<(script|pre|style|textarea)[\\s>][\\s\\S]*?(?:</\\1>[^\\n]*\\n*|$)|comment[^\\n]*(\\n+|$)|<\\?[\\s\\S]*?(?:\\?>[^\\n]*\\n*|$)|<![A-Z][\\s\\S]*?(?:>[^\\n]*\\n*|$)|<!\\[CDATA\\[[\\s\\S]*?(?:\\]\\]>[^\\n]*\\n*|$)|</?(tag)(?: +|\\n|/?>)[\\s\\S]*?(?:(?:\\n[ 	]*)+\\n|$)|<(?!script|pre|style|textarea)([a-z][\\w-]*)(?:attribute)*? */?>(?=[ \\t]*(?:\\n|$))[\\s\\S]*?(?:(?:\\n[ 	]*)+\\n|$)|</(?!script|pre|style|textarea)[a-z][\\w-]*\\s*>(?=[ \\t]*(?:\\n|$))[\\s\\S]*?(?:(?:\\n[ 	]*)+\\n|$))", "i").replace("comment", X).replace("tag", Q).replace("attribute", / +[a-zA-Z:_][\w.:-]*(?: *= *"[^"\n]*"| *= *'[^'\n]*'| *= *[^\s"'=<>`]+)?/).getRegex();
var le = (l) => k(K).replace("hr", q).replace("heading", " {0,3}#{1,6}(?:\\s|$)").replace("|lheading", "").replace("|table", "").replace("blockquote", " {0,3}>").replace("fences", " {0,3}(?:`{3,}(?=[^`\\n]*(?:\\n|$))|~~~)[^\\n]*(?:\\n|$)").replace("list", l).replace("html", "</?(?:tag)(?: +|\\n|/?>)|<(?:script|pre|style|textarea|!--)").replace("tag", Q).getRegex();
var ze = le(/ {0,3}(?:[*+-]|1[.)])[ \t]+[^ \t\n]/);
var Me = le(/ {0,3}(?:[*+-]|\d{1,9}[.)])(?:[ \t]|\n|$)/);
var J = {
	blockquote: k(/^( {0,3}> ?(paragraph|[^\n]*)(?:\n|$))+/).replace("paragraph", Me).getRegex(),
	code: we,
	def: $e,
	fences: ye,
	heading: Pe,
	hr: q,
	html: Ee,
	lheading: ae,
	list: Le,
	newline: Te,
	paragraph: ze,
	table: z,
	text: _e
};
var se = k("^ *([^\\n ].*)\\n {0,3}((?:\\| *)?:?-+:? *(?:\\| *:?-+:? *)*(?:\\| *)?)(?:\\n((?:(?! *\\n|hr|heading|blockquote|code|fences|list|html).*(?:\\n|$))*)\\n*|$)").replace("hr", q).replace("heading", " {0,3}#{1,6}(?:\\s|$)").replace("blockquote", " {0,3}>").replace("code", "(?: {4}| {0,3}	)[^\\n]").replace("fences", " {0,3}(?:`{3,}(?=[^`\\n]*(?:\\n|$))|~~~)[^\\n]*(?:\\n|$)").replace("list", " {0,3}(?:[*+-]|1[.)])[ \\t]").replace("html", "</?(?:tag)(?: +|\\n|/?>)|<(?:script|pre|style|textarea|!--)").replace("tag", Q).getRegex();
var Ie = {
	...J,
	lheading: Se,
	table: se,
	paragraph: k(K).replace("hr", q).replace("heading", " {0,3}#{1,6}(?:\\s|$)").replace("|lheading", "").replace("table", se).replace("blockquote", " {0,3}>").replace("fences", " {0,3}(?:`{3,}(?=[^`\\n]*(?:\\n|$))|~~~)[^\\n]*(?:\\n|$)").replace("list", " {0,3}(?:[*+-]|1[.)])[ \\t]+[^ \\t\\n]").replace("html", "</?(?:tag)(?: +|\\n|/?>)|<(?:script|pre|style|textarea|!--)").replace("tag", Q).getRegex()
};
var Ce = {
	...J,
	html: k(`^ *(?:comment *(?:\\n|\\s*$)|<(tag)[\\s\\S]+?</\\1> *(?:\\n{2,}|\\s*$)|<tag(?:"[^"]*"|'[^']*'|\\s[^'"/>\\s]*)*?/?> *(?:\\n{2,}|\\s*$))`).replace("comment", X).replace(/tag/g, "(?!(?:a|em|strong|small|s|cite|q|dfn|abbr|data|time|code|var|samp|kbd|sub|sup|i|b|u|mark|ruby|rt|rp|bdi|bdo|span|br|wbr|ins|del|img)\\b)\\w+(?!:|[^\\w\\s@]*@)\\b").getRegex(),
	def: /^ *\[([^\]]+)\]: *<?([^\s>]+)>?(?: +(["(][^\n]+[")]))? *(?:\n+|$)/,
	heading: /^(#{1,6})(.*)(?:\n+|$)/,
	fences: z,
	lheading: /^(.+?)\n {0,3}(=+|-+) *(?:\n+|$)/,
	paragraph: k(K).replace("hr", q).replace("heading", ` *#{1,6} *[^
]`).replace("lheading", ae).replace("|table", "").replace("blockquote", " {0,3}>").replace("|fences", "").replace("|list", "").replace("|html", "").replace("|tag", "").getRegex()
};
var Be = /^\\([!"#$%&'()*+,\-./:;<=>?@\[\]\\^_`{|}~])/;
var De = /^(`+)([^`]|[^`][\s\S]*?[^`])\1(?!`)/;
var ue = /^( {2,}|\\)\n(?!\s*$)/;
var qe = /^(`+|[^`])(?:(?= {2,}\n)|[\s\S]*?(?:(?=[\\<!\[`*_]|\b_|$)|[^ ](?= {2,}\n)))/;
var _ = /[\p{P}\p{S}]/u;
var C = /[\s\p{P}\p{S}]/u;
var v = /[^\s\p{P}\p{S}]/u;
var ve = k(/^((?![*_])punctSpace)/, "u").replace(/punctSpace/g, C).getRegex();
var He = /[\p{Pi}\p{Ps}"']/u;
var pe = /(?!~)[\p{P}\p{S}]/u;
var Ze = /(?!~)[\s\p{P}\p{S}]/u;
var Ge = /(?:[^\s\p{P}\p{S}]|~)/u;
var Qe = k(/link|precode-code|html/, "g").replace("link", /\[(?:[^\[\]`]|(?<a>`+)[^`]+\k<a>(?!`))*?\]\((?:\\[\s\S]|[^\\\(\)]|\((?:\\[\s\S]|[^\\\(\)])*\))*\)/).replace("precode-", Oe ? "(?<!`)()" : "(^^|[^`])").replace("code", /(?<b>`+)[^`]+\k<b>(?!`)/).replace("html", /<(?! )[^<>]*?>/).getRegex();
var ce = /^(?:\*+(?:((?!\*)punct)|([^\s*]))?)|^_+(?:((?!_)punct)|([^\s_]))?/;
var Ne = k(ce, "u").replace(/punct/g, _).getRegex();
var je = k(ce, "u").replace(/punct/g, pe).getRegex();
var Ue = k(/^(?:\*+(?:((?!\*)(?!openQuote)punct)|([^\s*]))?)|^_+(?:((?!_)(?!openQuote)punct)|([^\s_]))?/, "u").replace(/openQuote/g, He).replace(/punct/g, _).getRegex();
var he = "^[^_*]*?__[^_*]*?\\*[^_*]*?(?=__)|[^*]+(?=[^*])|(?!\\*)punct(\\*+)(?=[\\s]|$)|notPunctSpace(\\*+)(?!\\*)(?=punctSpace|$)|(?!\\*)punctSpace(\\*+)(?=notPunctSpace)|[\\s](\\*+)(?!\\*)(?=punct)|(?!\\*)punct(\\*+)(?!\\*)(?=punct)|notPunctSpace(\\*+)(?=notPunctSpace)";
var Ke = k(he, "gu").replace(/notPunctSpace/g, v).replace(/punctSpace/g, C).replace(/punct/g, _).getRegex();
var We = k(he, "gu").replace(/notPunctSpace/g, Ge).replace(/punctSpace/g, Ze).replace(/punct/g, pe).getRegex();
var Je = k("^[^_*]*?__[^_*]*?\\*[^_*]*?(?=__)|[^*]+(?=[^*])|(?!\\*)punct(\\*+)(?=[\\s]|$)|notPunctSpace(\\*+)(?!\\*)(?=punctSpace|$)|(?!\\*)[\\s](\\*+)(?=notPunctSpace)|[\\s](\\*+)(?!\\*)(?=punct)|(?!\\*)punct(\\*+)(?!\\*)(?=punct)|(?:(?!\\*)punct|notPunctSpace)(\\*+)(?!\\*)(?=notPunctSpace)", "gu").replace(/notPunctSpace/g, v).replace(/punctSpace/g, C).replace(/punct/g, _).getRegex();
var Ve = k("^[^_*]*?\\*\\*[^_*]*?_[^_*]*?(?=\\*\\*)|[^_]+(?=[^_])|(?!_)punct(_+)(?=[\\s]|$)|notPunctSpace(_+)(?!_)(?=punctSpace|$)|(?!_)punctSpace(_+)(?=notPunctSpace)|[\\s](_+)(?!_)(?=punct)|(?!_)punct(_+)(?!_)(?=punct)", "gu").replace(/notPunctSpace/g, v).replace(/punctSpace/g, C).replace(/punct/g, _).getRegex();
var et = k("^[^_*]*?\\*\\*[^_*]*?_[^_*]*?(?=\\*\\*)|[^_]+(?=[^_])|(?!_)punct(_+)(?=[\\s]|$)|notPunctSpace(_+)(?!_)(?=punctSpace|$)|(?!_)[\\s](_+)(?=notPunctSpace)|[\\s](_+)(?!_)(?=punct)|(?!_)punct(_+)(?!_)(?=punct)|(?:(?!_)punct|notPunctSpace)(_+)(?!_)(?=notPunctSpace)", "gu").replace(/notPunctSpace/g, v).replace(/punctSpace/g, C).replace(/punct/g, _).getRegex();
var tt = k(/^~~?(?:((?!~)punct)|[^\s~])/, "u").replace(/punct/g, _).getRegex();
var rt = k("^[^~]+(?=[^~])|(?!~)punct(~~?)(?=[\\s]|$)|notPunctSpace(~~?)(?!~)(?=punctSpace|$)|(?!~)punctSpace(~~?)(?=notPunctSpace)|[\\s](~~?)(?!~)(?=punct)|(?!~)punct(~~?)(?!~)(?=punct)|notPunctSpace(~~?)(?=notPunctSpace)", "gu").replace(/notPunctSpace/g, v).replace(/punctSpace/g, C).replace(/punct/g, _).getRegex();
var st = k(/\\(punct)/, "gu").replace(/punct/g, _).getRegex();
var it = k(/^<(scheme:[^\s\x00-\x1f<>]*|email)>/).replace("scheme", /[a-zA-Z][a-zA-Z0-9+.-]{1,31}/).replace("email", /[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+(@)[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)+(?![-_])/).getRegex();
var ot = k(X).replace("(?:-->|$)", "-->").getRegex();
var at = k("^comment|^</[a-zA-Z][\\w:-]*\\s*>|^<[a-zA-Z][\\w-]*(?:attribute)*?\\s*/?>|^<\\?[\\s\\S]*?\\?>|^<![a-zA-Z]+\\s[\\s\\S]*?>|^<!\\[CDATA\\[[\\s\\S]*?\\]\\]>").replace("comment", ot).replace("attribute", /\s+[a-zA-Z:_][\w.:-]*(?:\s*=\s*"[^"]*"|\s*=\s*'[^']*'|\s*=\s*[^\s"'=<>`]+)?/).getRegex();
var G = /(?:\[(?:\\[\s\S]|[^\[\]\\])*\]|\\[\s\S]|`+(?!`)[^`]*?`+(?!`)|``+(?=\])|[^\[\]\\`])*?/;
var lt = k(/^!?\[(label)\]\(\s*(href)(?:(?:[ \t]+(?:\n[ \t]*)?|\n[ \t]*)(title))?\s*\)/).replace("label", G).replace("href", /<(?:\\.|[^\n<>\\])+>|[^ \t\n\x00-\x1f]+|(?=\))/).replace("title", /"(?:\\"?|[^"\\])*"|'(?:\\'?|[^'\\])*'|\((?:\\\)?|[^)\\])*\)/).getRegex();
var ke = k(/^!?\[(label)\]\[(ref)\]/).replace("label", G).replace("ref", W).getRegex();
var de = k(/^!?\[(ref)\](?:\[\])?/).replace("ref", W).getRegex();
var ut = k("reflink|nolink(?!\\()", "g").replace("reflink", ke).replace("nolink", de).getRegex();
var ie = /[hH][tT][tT][pP][sS]?|[fF][tT][pP]/;
var V = {
	_backpedal: z,
	anyPunctuation: st,
	autolink: it,
	blockSkip: Qe,
	br: ue,
	code: De,
	del: z,
	delLDelim: z,
	delRDelim: z,
	emStrongLDelim: Ne,
	emStrongRDelimAst: Ke,
	emStrongRDelimUnd: Ve,
	escape: Be,
	link: lt,
	nolink: de,
	punctuation: ve,
	reflink: ke,
	reflinkSearch: ut,
	tag: at,
	text: qe,
	url: z
};
var pt = {
	...V,
	emStrongLDelim: Ue,
	emStrongRDelimAst: Je,
	emStrongRDelimUnd: et,
	link: k(/^!?\[(label)\]\((.*?)\)/).replace("label", G).getRegex(),
	reflink: k(/^!?\[(label)\]\s*\[([^\]]*)\]/).replace("label", G).getRegex()
};
var F = {
	...V,
	emStrongRDelimAst: We,
	emStrongLDelim: je,
	delLDelim: tt,
	delRDelim: rt,
	url: k(/^((?:protocol):\/\/|www\.)(?:[a-zA-Z0-9\-]+\.?)+[^\s<]*|^email/).replace("protocol", ie).replace("email", /[A-Za-z0-9._+-]+(@)[a-zA-Z0-9-_]+(?:\.[a-zA-Z0-9-_]*[a-zA-Z0-9])+(?![-_])/).getRegex(),
	_backpedal: /(?:[^?!.,:;*_'"~()&]+|\([^)]*\)|&(?![a-zA-Z0-9]+;$)|[?!.,:;*_'"~)]+(?!$))+/,
	del: /^(~~?)(?=[^\s~])((?:\\[\s\S]|[^\\])*?(?:\\[\s\S]|[^\s~\\]))\1(?=[^~]|$)/,
	text: k(/^(`+|~+|[^`~])(?:(?=[`~])|(?= {2,}\n)|(?=[a-zA-Z0-9.!#$%&'*+\/=?_`{\|}~-]+@)|[\s\S]*?(?:(?=[\\<!\[`*~_]|\b_|protocol:\/\/|www\.|$)|[^ ](?= {2,}\n)|[^a-zA-Z0-9.!#$%&'*+\/=?_`{\|}~-](?=[a-zA-Z0-9.!#$%&'*+\/=?_`{\|}~-]+@)))/).replace("protocol", ie).getRegex()
};
var ct = {
	...F,
	br: k(ue).replace("{2,}", "*").getRegex(),
	text: k(F.text).replace("\\b_", "\\b_| {2,}\\n").replace(/\{2,\}/g, "*").getRegex()
};
var H = {
	normal: J,
	gfm: Ie,
	pedantic: Ce
};
var B = {
	normal: V,
	gfm: F,
	breaks: ct,
	pedantic: pt
};
var ht = {
	"&": "&amp;",
	"<": "&lt;",
	">": "&gt;",
	"\"": "&quot;",
	"'": "&#39;"
};
var ge = (l) => ht[l];
function T(l, e) {
	if (e) {
		if (m.escapeTest.test(l)) return l.replace(m.escapeReplace, ge);
	} else if (m.escapeTestNoEncode.test(l)) return l.replace(m.escapeReplaceNoEncode, ge);
	return l;
}
function Y(l) {
	try {
		l = encodeURI(l).replace(m.percentDecode, "%");
	} catch {
		return null;
	}
	return l;
}
function ee(l, e) {
	let n = l.replace(m.findPipe, (r, i, o) => {
		let u = !1, a = i;
		for (; --a >= 0 && o[a] === "\\";) u = !u;
		return u ? "|" : " |";
	}).split(m.splitPipe), s = 0;
	if (n[0].trim() || n.shift(), n.length > 0 && !n.at(-1)?.trim() && n.pop(), e) if (n.length > e) n.splice(e);
	else for (; n.length < e;) n.push("");
	for (; s < n.length; s++) n[s] = n[s].trim().replace(m.slashPipe, "|");
	return n;
}
function $(l, e, t) {
	let n = l.length;
	if (n === 0) return "";
	let s = 0;
	for (; s < n;) {
		let r = l.charAt(n - s - 1);
		if (r === e && !t) s++;
		else if (r !== e && t) s++;
		else break;
	}
	return l.slice(0, n - s);
}
function te(l) {
	let e = l.split(`
`), t = e.length - 1;
	for (; t >= 0 && m.blankLine.test(e[t]);) t--;
	return e.length - t <= 2 ? l : e.slice(0, t + 1).join(`
`);
}
function fe(l, e) {
	if (l.indexOf(e[1]) === -1) return -1;
	let t = 0;
	for (let n = 0; n < l.length; n++) if (l[n] === "\\") n++;
	else if (l[n] === e[0]) t++;
	else if (l[n] === e[1] && (t--, t < 0)) return n;
	return t > 0 ? -2 : -1;
}
function me(l, e = 0) {
	let t = e, n = "";
	for (let s of l) if (s === "	") {
		let r = 4 - t % 4;
		n += " ".repeat(r), t += r;
	} else n += s, t++;
	return n;
}
function xe(l, e, t, n, s) {
	let r = e.href, i = e.title || null, o = l[1].replace(s.other.outputLinkReplace, "$1"), u = l[0].charAt(0) === "!";
	n.state.inLink = !0;
	let a = n.state.linkEmitted, p = n.state.inRawBlock;
	n.state.linkEmitted = !1;
	let c = n.inlineTokens(o), h = n.state.linkEmitted;
	if (n.state.linkEmitted = a, n.state.inLink = !1, !u) {
		if (h) {
			n.state.inRawBlock = p;
			return;
		}
		n.state.linkEmitted = !0;
	}
	return {
		type: u ? "image" : "link",
		raw: t,
		href: r,
		title: i,
		text: o,
		tokens: c
	};
}
function kt(l, e, t) {
	let n = l.match(t.other.indentCodeCompensation);
	if (n === null) return e;
	let s = n[1];
	return e.split(`
`).map((r) => {
		let i = r.match(t.other.beginningSpace);
		if (i === null) return r;
		let [o] = i;
		return o.length >= s.length ? r.slice(s.length) : r;
	}).join(`
`);
}
var y = class {
	options;
	rules;
	lexer;
	constructor(e) {
		this.options = e || R;
	}
	space(e) {
		let t = this.rules.block.newline.exec(e);
		if (t && t[0].length > 0) return {
			type: "space",
			raw: t[0]
		};
	}
	code(e) {
		let t = this.rules.block.code.exec(e);
		if (t) {
			let n = this.options.pedantic ? t[0] : te(t[0]);
			return {
				type: "code",
				raw: n,
				codeBlockStyle: "indented",
				text: n.replace(this.rules.other.codeRemoveIndent, "")
			};
		}
	}
	fences(e) {
		let t = this.rules.block.fences.exec(e);
		if (t) {
			let n = t[0], s = kt(n, t[3] || "", this.rules);
			return {
				type: "code",
				raw: n,
				lang: t[2] ? t[2].trim().replace(this.rules.inline.anyPunctuation, "$1") : t[2],
				text: s
			};
		}
	}
	heading(e) {
		let t = this.rules.block.heading.exec(e);
		if (t) {
			let n = t[2].trim();
			if (this.rules.other.endingHash.test(n)) {
				let s = $(n, "#");
				(this.options.pedantic || !s || this.rules.other.endingSpaceChar.test(s)) && (n = s.trim());
			}
			return {
				type: "heading",
				raw: $(t[0], `
`),
				depth: t[1].length,
				text: n,
				tokens: this.lexer.inline(n)
			};
		}
	}
	hr(e) {
		let t = this.rules.block.hr.exec(e);
		if (t) return {
			type: "hr",
			raw: $(t[0], `
`)
		};
	}
	blockquote(e) {
		let t = this.rules.block.blockquote.exec(e);
		if (t) {
			let n = $(t[0], `
`).split(`
`), s = "", r = "", i = [];
			for (; n.length > 0;) {
				let o = !1, u = [], a = 0;
				for (; a < n.length; a++) if (this.rules.other.blockquoteStart.test(n[a])) u.push(n[a]), o = !0;
				else if (!o) u.push(n[a]);
				else break;
				n = n.slice(a);
				let p = u.join(`
`), c = p.replace(this.rules.other.blockquoteSetextReplace, `
    $1`).replace(this.rules.other.blockquoteSetextReplace2, "");
				s = s ? `${s}
${p}` : p, r = r ? `${r}
${c}` : c;
				let h = this.lexer.state.top;
				if (this.lexer.state.top = !0, this.lexer.blockTokens(c, i, !0), this.lexer.state.top = h, n.length === 0) break;
				let d = i.at(-1);
				if (d?.type === "code") break;
				if (d?.type === "blockquote") {
					let O = d, g = n.join(`
`), w = O.raw + `
` + g.replace(this.rules.other.blockquoteSetextReplace2, ""), E = this.blockquote(w);
					i[i.length - 1] = E, s = `${s}
${g}`, r = r.substring(0, r.length - O.text.length) + E.text;
					break;
				} else if (d?.type === "list") {
					let O = d, g = O.raw + `
` + n.join(`
`), w = this.list(g);
					i[i.length - 1] = w, s = s.substring(0, s.length - d.raw.length) + w.raw, r = r.substring(0, r.length - O.raw.length) + w.raw, n = g.substring(i.at(-1).raw.length).split(`
`);
					continue;
				}
			}
			return {
				type: "blockquote",
				raw: s,
				tokens: i,
				text: r
			};
		}
	}
	list(e) {
		let t = this.rules.block.list.exec(e);
		if (t) {
			let n = t[1].trim(), s = n.length > 1, r = {
				type: "list",
				raw: "",
				ordered: s,
				start: s ? +n.slice(0, -1) : "",
				loose: !1,
				items: []
			};
			n = s ? `\\d{1,9}\\${n.slice(-1)}` : `\\${n}`, this.options.pedantic && (n = s ? n : "[*+-]");
			let i = this.rules.other.listItemRegex(n), o = !1;
			for (; e;) {
				let a = !1, p = "", c = "";
				if (!(t = i.exec(e)) || this.rules.block.hr.test(e)) break;
				p = t[0], e = e.substring(p.length);
				let h = me(t[2].split(`
`, 1)[0], t[1].length), d = e.split(`
`, 1)[0], O = !h.trim(), g = 0;
				if (this.options.pedantic ? (g = 2, c = h.trimStart()) : O ? g = t[1].length + 1 : (g = h.search(this.rules.other.nonSpaceChar), g = g > 4 ? 1 : g, c = h.slice(g), g += t[1].length), O && this.rules.other.blankLine.test(d) && (p += d + `
`, e = e.substring(d.length + 1), a = !0), !a) {
					let w = this.rules.other.nextBulletRegex(g), E = this.rules.other.hrRegex(g), ne = this.rules.other.fencesBeginRegex(g), re = this.rules.other.headingBeginRegex(g), be = this.rules.other.htmlBeginRegex(g), Re = this.rules.other.blockquoteBeginRegex(g);
					for (; e;) {
						let N = e.split(`
`, 1)[0], D;
						if (d = N, this.options.pedantic ? (d = d.replace(this.rules.other.listReplaceNesting, "  "), D = d) : D = d.replace(this.rules.other.tabCharGlobal, "    "), ne.test(d) || re.test(d) || be.test(d) || Re.test(d) || w.test(d) || E.test(d)) break;
						if (D.search(this.rules.other.nonSpaceChar) >= g || !d.trim()) c += `
` + D.slice(g);
						else {
							if (O || h.replace(this.rules.other.tabCharGlobal, "    ").search(this.rules.other.nonSpaceChar) >= 4 || ne.test(h) || re.test(h) || E.test(h)) break;
							c += `
` + d;
						}
						O = !d.trim(), p += N + `
`, e = e.substring(N.length + 1), h = D.slice(g);
					}
				}
				r.loose || (o ? r.loose = !0 : this.rules.other.doubleBlankLine.test(p) && (o = !0)), r.items.push({
					type: "list_item",
					raw: p,
					task: !!this.options.gfm && this.rules.other.listIsTask.test(c),
					loose: !1,
					text: c,
					tokens: []
				}), r.raw += p;
			}
			let u = r.items.at(-1);
			if (u) u.raw = u.raw.trimEnd(), u.text = u.text.trimEnd();
			else return;
			r.raw = r.raw.trimEnd();
			for (let a of r.items) if (this.lexer.state.top = !1, a.tokens = this.lexer.blockTokens(a.text, []), !r.loose) {
				let p = a.tokens.filter((h) => h.type === "space");
				r.loose = p.length > 0 && p.some((h) => this.rules.other.anyLine.test(h.raw));
			}
			for (let a of r.items) {
				let p = a.tokens[0];
				if (a.task && (p?.type === "text" || p?.type === "paragraph")) {
					a.text = a.text.replace(this.rules.other.listReplaceTask, ""), p.raw = p.raw.replace(this.rules.other.listReplaceTask, ""), p.text = p.text.replace(this.rules.other.listReplaceTask, "");
					for (let h = this.lexer.inlineQueue.length - 1; h >= 0; h--) if (this.rules.other.listIsTask.test(this.lexer.inlineQueue[h].src)) {
						this.lexer.inlineQueue[h].src = this.lexer.inlineQueue[h].src.replace(this.rules.other.listReplaceTask, "");
						break;
					}
					let c = this.rules.other.listTaskCheckbox.exec(a.raw);
					if (c) {
						let h = {
							type: "checkbox",
							raw: c[0] + " ",
							checked: c[0] !== "[ ]"
						};
						a.checked = h.checked, r.loose ? a.tokens[0] && ["paragraph", "text"].includes(a.tokens[0].type) && "tokens" in a.tokens[0] && a.tokens[0].tokens ? (a.tokens[0].raw = h.raw + a.tokens[0].raw, a.tokens[0].text = h.raw + a.tokens[0].text, a.tokens[0].tokens.unshift(h)) : a.tokens.unshift({
							type: "paragraph",
							raw: h.raw,
							text: h.raw,
							tokens: [h]
						}) : a.tokens.unshift(h);
					}
				} else a.task && (a.task = !1);
			}
			if (r.loose) for (let a of r.items) {
				a.loose = !0;
				for (let p of a.tokens) p.type === "text" && (p.type = "paragraph");
			}
			return r;
		}
	}
	html(e) {
		let t = this.rules.block.html.exec(e);
		if (t) {
			let n = te(t[0]);
			return {
				type: "html",
				block: !0,
				raw: n,
				pre: t[1] === "pre" || t[1] === "script" || t[1] === "style",
				text: n
			};
		}
	}
	def(e) {
		let t = this.rules.block.def.exec(e);
		if (t) {
			let n = t[1].toLowerCase().replace(this.rules.other.multipleSpaceGlobal, " "), s = t[2] ? t[2].replace(this.rules.other.hrefBrackets, "$1").replace(this.rules.inline.anyPunctuation, "$1") : "", r = t[3] ? t[3].substring(1, t[3].length - 1).replace(this.rules.inline.anyPunctuation, "$1") : t[3];
			return {
				type: "def",
				tag: n,
				raw: $(t[0], `
`),
				href: s,
				title: r
			};
		}
	}
	table(e) {
		let t = this.rules.block.table.exec(e);
		if (!t || !this.rules.other.tableDelimiter.test(t[2])) return;
		let n = ee(t[1]), s = t[2].replace(this.rules.other.tableAlignChars, "").split("|"), r = t[3]?.trim() ? t[3].replace(this.rules.other.tableRowBlankLine, "").split(`
`) : [], i = {
			type: "table",
			raw: $(t[0], `
`),
			header: [],
			align: [],
			rows: []
		};
		if (n.length === s.length) {
			for (let o of s) this.rules.other.tableAlignRight.test(o) ? i.align.push("right") : this.rules.other.tableAlignCenter.test(o) ? i.align.push("center") : this.rules.other.tableAlignLeft.test(o) ? i.align.push("left") : i.align.push(null);
			for (let o = 0; o < n.length; o++) i.header.push({
				text: n[o],
				tokens: this.lexer.inline(n[o]),
				header: !0,
				align: i.align[o]
			});
			for (let o of r) i.rows.push(ee(o, i.header.length).map((u, a) => ({
				text: u,
				tokens: this.lexer.inline(u),
				header: !1,
				align: i.align[a]
			})));
			return i;
		}
	}
	lheading(e) {
		let t = this.rules.block.lheading.exec(e);
		if (t) {
			let n = t[1].trim();
			return {
				type: "heading",
				raw: $(t[0], `
`),
				depth: t[2].charAt(0) === "=" ? 1 : 2,
				text: n,
				tokens: this.lexer.inline(n)
			};
		}
	}
	paragraph(e) {
		let t = this.rules.block.paragraph.exec(e);
		if (t) {
			let n = t[1].charAt(t[1].length - 1) === `
` ? t[1].slice(0, -1) : t[1];
			return {
				type: "paragraph",
				raw: t[0],
				text: n,
				tokens: this.lexer.inline(n)
			};
		}
	}
	text(e) {
		let t = this.rules.block.text.exec(e);
		if (t) return {
			type: "text",
			raw: t[0],
			text: t[0],
			tokens: this.lexer.inline(t[0])
		};
	}
	escape(e) {
		let t = this.rules.inline.escape.exec(e);
		if (t) return {
			type: "escape",
			raw: t[0],
			text: t[1]
		};
	}
	tag(e) {
		let t = this.rules.inline.tag.exec(e);
		if (t) return !this.lexer.state.inLink && this.rules.other.startATag.test(t[0]) ? this.lexer.state.inLink = !0 : this.lexer.state.inLink && this.rules.other.endATag.test(t[0]) && (this.lexer.state.inLink = !1), !this.lexer.state.inRawBlock && this.rules.other.startPreScriptTag.test(t[0]) ? this.lexer.state.inRawBlock = !0 : this.lexer.state.inRawBlock && this.rules.other.endPreScriptTag.test(t[0]) && (this.lexer.state.inRawBlock = !1), {
			type: "html",
			raw: t[0],
			inLink: this.lexer.state.inLink,
			inRawBlock: this.lexer.state.inRawBlock,
			block: !1,
			text: t[0]
		};
	}
	link(e) {
		let t = this.rules.inline.link.exec(e);
		if (t) {
			let n = t[2].trim();
			if (!this.options.pedantic && this.rules.other.startAngleBracket.test(n)) {
				if (!this.rules.other.endAngleBracket.test(n)) return;
				let i = $(n.slice(0, -1), "\\");
				if ((n.length - i.length) % 2 === 0) return;
			} else {
				let i = fe(t[2], "()");
				if (i === -2) return;
				if (i > -1) {
					let u = (t[0].indexOf("!") === 0 ? 5 : 4) + t[1].length + i;
					t[2] = t[2].substring(0, i), t[0] = t[0].substring(0, u).trim(), t[3] = "";
				}
			}
			let s = t[2], r = "";
			if (this.options.pedantic) {
				let i = this.rules.other.pedanticHrefTitle.exec(s);
				i && (s = i[1], r = i[3]);
			} else r = t[3] ? t[3].slice(1, -1) : "";
			return s = s.trim(), this.rules.other.startAngleBracket.test(s) && (this.options.pedantic && !this.rules.other.endAngleBracket.test(n) ? s = s.slice(1) : s = s.slice(1, -1)), xe(t, {
				href: s && s.replace(this.rules.inline.anyPunctuation, "$1"),
				title: r && r.replace(this.rules.inline.anyPunctuation, "$1")
			}, t[0], this.lexer, this.rules);
		}
	}
	reflink(e, t) {
		let n;
		if ((n = this.rules.inline.reflink.exec(e)) || (n = this.rules.inline.nolink.exec(e))) {
			let r = t[(n[2] || n[1]).replace(this.rules.other.multipleSpaceGlobal, " ").toLowerCase()];
			if (!r) {
				let i = n[0].charAt(0);
				return {
					type: "text",
					raw: i,
					text: i
				};
			}
			return xe(n, r, n[0], this.lexer, this.rules);
		}
	}
	emStrong(e, t, n = "") {
		let s = this.rules.inline.emStrongLDelim.exec(e);
		if (!s || !s[1] && !s[2] && !s[3] && !s[4] || s[4] && n.match(this.rules.other.unicodeAlphaNumeric)) return;
		if (!(s[1] || s[3] || "") || !n || this.rules.inline.punctuation.exec(n)) {
			let i = [...s[0]].length - 1, o, u, a = i, p = 0, c = s[0][0], h = n === c, d = c === "*" ? this.rules.inline.emStrongRDelimAst : this.rules.inline.emStrongRDelimUnd;
			for (d.lastIndex = 0, t = t.slice(-1 * e.length + i); (s = d.exec(t)) !== null;) {
				if (o = s[1] || s[2] || s[3] || s[4] || s[5] || s[6], !o) continue;
				if (u = [...o].length, s[3] || s[4]) {
					a += u;
					continue;
				} else if (s[5] || s[6]) {
					if (i % 3 && !((i + u) % 3)) {
						p += u;
						continue;
					}
					if (h) break;
				}
				if (a -= u, a > 0) continue;
				u = Math.min(u, u + a + p);
				let O = [...s[0]][0].length, g = e.slice(0, i + s.index + O + u);
				if (Math.min(i, u) % 2) {
					let E = g.slice(1, -1);
					return {
						type: "em",
						raw: g,
						text: E,
						tokens: this.lexer.inlineTokens(E)
					};
				}
				let w = g.slice(2, -2);
				return {
					type: "strong",
					raw: g,
					text: w,
					tokens: this.lexer.inlineTokens(w)
				};
			}
		}
	}
	codespan(e) {
		let t = this.rules.inline.code.exec(e);
		if (t) {
			let n = t[2].replace(this.rules.other.newLineCharGlobal, " "), s = this.rules.other.nonSpaceChar.test(n), r = this.rules.other.startingSpaceChar.test(n) && this.rules.other.endingSpaceChar.test(n);
			return s && r && (n = n.substring(1, n.length - 1)), {
				type: "codespan",
				raw: t[0],
				text: n
			};
		}
	}
	br(e) {
		let t = this.rules.inline.br.exec(e);
		if (t) return {
			type: "br",
			raw: t[0]
		};
	}
	del(e, t, n = "") {
		let s = this.rules.inline.delLDelim.exec(e);
		if (!s) return;
		if (!(s[1] || "") || !n || this.rules.inline.punctuation.exec(n)) {
			let i = [...s[0]].length - 1, o, u, a = i, p = this.rules.inline.delRDelim;
			for (p.lastIndex = 0, t = t.slice(-1 * e.length + i); (s = p.exec(t)) !== null;) {
				if (o = s[1] || s[2] || s[3] || s[4] || s[5] || s[6], !o || (u = [...o].length, u !== i)) continue;
				if (s[3] || s[4]) {
					a += u;
					continue;
				}
				if (a -= u, a > 0) continue;
				u = Math.min(u, u + a);
				let c = [...s[0]][0].length, h = e.slice(0, i + s.index + c + u), d = h.slice(i, -i);
				return {
					type: "del",
					raw: h,
					text: d,
					tokens: this.lexer.inlineTokens(d)
				};
			}
		}
	}
	autolink(e) {
		let t = this.rules.inline.autolink.exec(e);
		if (t) {
			let n, s;
			return t[2] === "@" ? (n = t[1], s = "mailto:" + n) : (n = t[1], s = n), {
				type: "link",
				raw: t[0],
				text: n,
				href: s,
				tokens: [{
					type: "text",
					raw: n,
					text: n
				}]
			};
		}
	}
	url(e) {
		let t;
		if (t = this.rules.inline.url.exec(e)) {
			let n, s;
			if (t[2] === "@") n = t[0], s = "mailto:" + n;
			else {
				let r;
				do
					r = t[0], t[0] = this.rules.inline._backpedal.exec(t[0])?.[0] ?? "";
				while (r !== t[0]);
				n = t[0], t[1] === "www." ? s = "http://" + t[0] : s = t[0];
			}
			return {
				type: "link",
				raw: t[0],
				text: n,
				href: s,
				tokens: [{
					type: "text",
					raw: n,
					text: n
				}]
			};
		}
	}
	inlineText(e) {
		let t = this.rules.inline.text.exec(e);
		if (t) {
			let n = this.lexer.state.inRawBlock;
			return {
				type: "text",
				raw: t[0],
				text: t[0],
				escaped: n
			};
		}
	}
};
var x = class l {
	tokens;
	options;
	state;
	inlineQueue;
	tokenizer;
	constructor(e) {
		this.tokens = [], this.tokens.links = Object.create(null), this.options = e || R, this.options.tokenizer = this.options.tokenizer || new y(), this.tokenizer = this.options.tokenizer, this.tokenizer.options = this.options, this.tokenizer.lexer = this, this.inlineQueue = [], this.state = {
			inLink: !1,
			inRawBlock: !1,
			linkEmitted: !1,
			top: !0
		};
		let t = {
			other: m,
			block: H.normal,
			inline: B.normal
		};
		this.options.pedantic ? (t.block = H.pedantic, t.inline = B.pedantic) : this.options.gfm && (t.block = H.gfm, this.options.breaks ? t.inline = B.breaks : t.inline = B.gfm), this.tokenizer.rules = t;
	}
	static get rules() {
		return {
			block: H,
			inline: B
		};
	}
	static lex(e, t) {
		return new l(t).lex(e);
	}
	static lexInline(e, t) {
		return new l(t).inlineTokens(e);
	}
	lex(e) {
		e = e.replace(m.carriageReturn, `
`), this.blockTokens(e, this.tokens);
		for (let t = 0; t < this.inlineQueue.length; t++) {
			let n = this.inlineQueue[t];
			this.inlineTokens(n.src, n.tokens);
		}
		return this.inlineQueue = [], this.tokens;
	}
	blockTokens(e, t = [], n = !1) {
		this.tokenizer.lexer = this, this.options.pedantic && (e = e.replace(m.tabCharGlobal, "    ").replace(m.spaceLine, ""));
		let s = 1 / 0;
		for (; e;) {
			if (e.length < s) s = e.length;
			else {
				this.infiniteLoopError(e.charCodeAt(0));
				break;
			}
			let r;
			if (this.options.extensions?.block?.some((o) => (r = o.call({ lexer: this }, e, t)) ? (e = e.substring(r.raw.length), t.push(r), !0) : !1)) continue;
			if (r = this.tokenizer.space(e)) {
				e = e.substring(r.raw.length);
				let o = t.at(-1);
				r.raw.length === 1 && o !== void 0 ? o.raw += `
` : t.push(r);
				continue;
			}
			if (r = this.tokenizer.code(e)) {
				e = e.substring(r.raw.length);
				let o = t.at(-1);
				o?.type === "paragraph" || o?.type === "text" ? (o.raw += (o.raw.endsWith(`
`) ? "" : `
`) + r.raw, o.text += `
` + r.text, this.inlineQueue.at(-1).src = o.text) : t.push(r);
				continue;
			}
			if (r = this.tokenizer.fences(e)) {
				e = e.substring(r.raw.length), t.push(r);
				continue;
			}
			if (r = this.tokenizer.heading(e)) {
				e = e.substring(r.raw.length), t.push(r);
				continue;
			}
			if (r = this.tokenizer.hr(e)) {
				e = e.substring(r.raw.length), t.push(r);
				continue;
			}
			if (r = this.tokenizer.blockquote(e)) {
				e = e.substring(r.raw.length), t.push(r);
				continue;
			}
			if (r = this.tokenizer.list(e)) {
				e = e.substring(r.raw.length), t.push(r);
				continue;
			}
			if (r = this.tokenizer.html(e)) {
				e = e.substring(r.raw.length), t.push(r);
				continue;
			}
			if (r = this.tokenizer.def(e)) {
				e = e.substring(r.raw.length);
				let o = t.at(-1);
				o?.type === "paragraph" || o?.type === "text" ? (o.raw += (o.raw.endsWith(`
`) ? "" : `
`) + r.raw, o.text += `
` + r.raw, this.inlineQueue.at(-1).src = o.text) : this.tokens.links[r.tag] || (this.tokens.links[r.tag] = {
					href: r.href,
					title: r.title
				}, t.push(r));
				continue;
			}
			if (r = this.tokenizer.table(e)) {
				e = e.substring(r.raw.length), t.push(r);
				continue;
			}
			if (r = this.tokenizer.lheading(e)) {
				e = e.substring(r.raw.length), t.push(r);
				continue;
			}
			let i = e;
			if (this.options.extensions?.startBlock) {
				let o = 1 / 0, u = e.slice(1), a;
				this.options.extensions.startBlock.forEach((p) => {
					a = p.call({ lexer: this }, u), typeof a == "number" && a >= 0 && (o = Math.min(o, a));
				}), o < 1 / 0 && o >= 0 && (i = e.substring(0, o + 1));
			}
			if (this.state.top && (r = this.tokenizer.paragraph(i))) {
				let o = t.at(-1);
				n && o?.type === "paragraph" ? (o.raw += (o.raw.endsWith(`
`) ? "" : `
`) + r.raw, o.text += `
` + r.text, this.inlineQueue.pop(), this.inlineQueue.at(-1).src = o.text) : t.push(r), n = i.length !== e.length, e = e.substring(r.raw.length);
				continue;
			}
			if (r = this.tokenizer.text(e)) {
				e = e.substring(r.raw.length);
				let o = t.at(-1);
				o?.type === "text" ? (o.raw += (o.raw.endsWith(`
`) ? "" : `
`) + r.raw, o.text += `
` + r.text, this.inlineQueue.pop(), this.inlineQueue.at(-1).src = o.text) : t.push(r);
				continue;
			}
			if (e) {
				this.infiniteLoopError(e.charCodeAt(0));
				break;
			}
		}
		return this.state.top = !0, t;
	}
	inline(e, t = []) {
		return this.inlineQueue.push({
			src: e,
			tokens: t
		}), t;
	}
	linkInText(e) {
		if (!e.includes("[")) return !1;
		let t = this.tokenizer.rules.inline.link;
		for (let n of e.matchAll(this.tokenizer.rules.inline.blockSkip)) if (t.test(n[0]) && e.charAt(n.index - 1) !== "!") return !0;
		for (let n of e.matchAll(this.tokenizer.rules.inline.reflinkSearch)) {
			let s = n[0], r = s.lastIndexOf("[");
			if (!(s.charAt(0) === "!" || !Object.hasOwn(this.tokens.links, s.slice(r + 1, -1))) && !(r > 1 && this.linkInText(s.slice(1, r - 1)))) return !0;
		}
		return !1;
	}
	inlineTokens(e, t = []) {
		this.tokenizer.lexer = this;
		let n = e;
		if (this.tokens.links && e.includes("[")) {
			let o = this.tokenizer.rules.inline.reflinkSearch, u = (a) => {
				let p = a.lastIndexOf("[");
				if (!Object.hasOwn(this.tokens.links, a.slice(p + 1, -1))) return a;
				if (p > 1 && a.charAt(0) !== "!") {
					let c = a.slice(1, p - 1);
					if (this.linkInText(c)) return "[" + c.replace(o, u) + "][" + "a".repeat(a.length - p - 2) + "]";
				}
				return "[" + "a".repeat(a.length - 2) + "]";
			};
			n = n.replace(o, u);
		}
		n = n.replace(this.tokenizer.rules.inline.anyPunctuation, (o) => "+".repeat(o.length)), n = n.replace(this.tokenizer.rules.inline.blockSkip, (o, u, a) => {
			let p = a ? a.length : 0;
			return o.slice(0, p) + "[" + "a".repeat(o.length - p - 2) + "]";
		}), n = this.options.hooks?.emStrongMask?.call({ lexer: this }, n) ?? n;
		let s = !1, r = "", i = 1 / 0;
		for (; e;) {
			if (e.length < i) i = e.length;
			else {
				this.infiniteLoopError(e.charCodeAt(0));
				break;
			}
			s || (r = ""), s = !1;
			let o;
			if (this.options.extensions?.inline?.some((a) => (o = a.call({ lexer: this }, e, t)) ? (e = e.substring(o.raw.length), t.push(o), !0) : !1)) continue;
			if (o = this.tokenizer.escape(e)) {
				e = e.substring(o.raw.length), t.push(o);
				continue;
			}
			if (o = this.tokenizer.tag(e)) {
				e = e.substring(o.raw.length), t.push(o);
				continue;
			}
			if (o = this.tokenizer.link(e)) {
				e = e.substring(o.raw.length), t.push(o);
				continue;
			}
			if (o = this.tokenizer.reflink(e, this.tokens.links)) {
				e = e.substring(o.raw.length);
				let a = t.at(-1);
				o.type === "text" && a?.type === "text" ? (a.raw += o.raw, a.text += o.text) : t.push(o);
				continue;
			}
			if (o = this.tokenizer.emStrong(e, n, r)) {
				e = e.substring(o.raw.length), t.push(o);
				continue;
			}
			if (o = this.tokenizer.codespan(e)) {
				e = e.substring(o.raw.length), t.push(o);
				continue;
			}
			if (o = this.tokenizer.br(e)) {
				e = e.substring(o.raw.length), t.push(o);
				continue;
			}
			if (o = this.tokenizer.del(e, n, r)) {
				e = e.substring(o.raw.length), t.push(o);
				continue;
			}
			if (o = this.tokenizer.autolink(e)) {
				e = e.substring(o.raw.length), t.push(o);
				continue;
			}
			if (!this.state.inLink && (o = this.tokenizer.url(e))) {
				e = e.substring(o.raw.length), t.push(o);
				continue;
			}
			let u = e;
			if (this.options.extensions?.startInline) {
				let a = 1 / 0, p = e.slice(1), c;
				this.options.extensions.startInline.forEach((h) => {
					c = h.call({ lexer: this }, p), typeof c == "number" && c >= 0 && (a = Math.min(a, c));
				}), a < 1 / 0 && a >= 0 && (u = e.substring(0, a + 1));
			}
			if (o = this.tokenizer.inlineText(u)) {
				e = e.substring(o.raw.length), o.raw.slice(-1) !== "_" && (r = o.raw.slice(-1)), s = !0;
				let a = t.at(-1);
				a?.type === "text" ? (a.raw += o.raw, a.text += o.text) : t.push(o);
				continue;
			}
			if (e) {
				this.infiniteLoopError(e.charCodeAt(0));
				break;
			}
		}
		return t;
	}
	infiniteLoopError(e) {
		let t = "Infinite loop on byte: " + e;
		if (this.options.silent) console.error(t);
		else throw new Error(t);
	}
};
var P = class {
	options;
	parser;
	constructor(e) {
		this.options = e || R;
	}
	space(e) {
		return "";
	}
	code({ text: e, lang: t, escaped: n }) {
		let s = (t || "").match(m.notSpaceStart)?.[0], r = e.replace(m.endingNewline, "") + `
`;
		return s ? "<pre><code class=\"language-" + T(s) + "\">" + (n ? r : T(r, !0)) + `</code></pre>
` : "<pre><code>" + (n ? r : T(r, !0)) + `</code></pre>
`;
	}
	blockquote({ tokens: e }) {
		return `<blockquote>
${this.parser.parse(e)}</blockquote>
`;
	}
	html({ text: e }) {
		return e;
	}
	def(e) {
		return "";
	}
	heading({ tokens: e, depth: t }) {
		return `<h${t}>${this.parser.parseInline(e)}</h${t}>
`;
	}
	hr(e) {
		return `<hr>
`;
	}
	list(e) {
		let t = e.ordered, n = e.start, s = "";
		for (let o = 0; o < e.items.length; o++) {
			let u = e.items[o];
			s += this.listitem(u);
		}
		let r = t ? "ol" : "ul", i = t && n !== 1 ? " start=\"" + n + "\"" : "";
		return "<" + r + i + `>
` + s + "</" + r + `>
`;
	}
	listitem(e) {
		return `<li>${this.parser.parse(e.tokens)}</li>
`;
	}
	checkbox({ checked: e }) {
		return "<input " + (e ? "checked=\"\" " : "") + "disabled=\"\" type=\"checkbox\"> ";
	}
	paragraph({ tokens: e }) {
		return `<p>${this.parser.parseInline(e)}</p>
`;
	}
	table(e) {
		let t = "", n = "";
		for (let r = 0; r < e.header.length; r++) n += this.tablecell(e.header[r]);
		t += this.tablerow({ text: n });
		let s = "";
		for (let r = 0; r < e.rows.length; r++) {
			let i = e.rows[r];
			n = "";
			for (let o = 0; o < i.length; o++) n += this.tablecell(i[o]);
			s += this.tablerow({ text: n });
		}
		return s && (s = `<tbody>${s}</tbody>`), `<table>
<thead>
` + t + `</thead>
` + s + `</table>
`;
	}
	tablerow({ text: e }) {
		return `<tr>
${e}</tr>
`;
	}
	tablecell(e) {
		let t = this.parser.parseInline(e.tokens), n = e.header ? "th" : "td";
		return (e.align ? `<${n} align="${e.align}">` : `<${n}>`) + t + `</${n}>
`;
	}
	strong({ tokens: e }) {
		return `<strong>${this.parser.parseInline(e)}</strong>`;
	}
	em({ tokens: e }) {
		return `<em>${this.parser.parseInline(e)}</em>`;
	}
	codespan({ text: e }) {
		return `<code>${T(e, !0)}</code>`;
	}
	br(e) {
		return "<br>";
	}
	del({ tokens: e }) {
		return `<del>${this.parser.parseInline(e)}</del>`;
	}
	link({ href: e, title: t, tokens: n }) {
		let s = this.parser.parseInline(n), r = Y(e);
		if (r === null) return s;
		e = r;
		let i = "<a href=\"" + e + "\"";
		return t && (i += " title=\"" + T(t) + "\""), i += ">" + s + "</a>", i;
	}
	image({ href: e, title: t, text: n, tokens: s }) {
		s && (n = this.parser.parseInline(s, this.parser.textRenderer));
		let r = Y(e);
		if (r === null) return T(n);
		e = r;
		let i = `<img src="${e}" alt="${T(n)}"`;
		return t && (i += ` title="${T(t)}"`), i += ">", i;
	}
	text(e) {
		return "tokens" in e && e.tokens ? this.parser.parseInline(e.tokens) : "escaped" in e && e.escaped ? e.text : T(e.text);
	}
};
var L = class {
	strong({ text: e }) {
		return e;
	}
	em({ text: e }) {
		return e;
	}
	codespan({ text: e }) {
		return e;
	}
	del({ text: e }) {
		return e;
	}
	html({ text: e }) {
		return e;
	}
	text({ text: e }) {
		return e;
	}
	link({ text: e }) {
		return "" + e;
	}
	image({ text: e }) {
		return "" + e;
	}
	br() {
		return "";
	}
	checkbox({ raw: e }) {
		return e;
	}
};
var b = class l {
	options;
	renderer;
	textRenderer;
	constructor(e) {
		this.options = e || R, this.options.renderer = this.options.renderer || new P(), this.renderer = this.options.renderer, this.renderer.options = this.options, this.renderer.parser = this, this.textRenderer = new L();
	}
	static parse(e, t) {
		return new l(t).parse(e);
	}
	static parseInline(e, t) {
		return new l(t).parseInline(e);
	}
	parse(e) {
		this.renderer.parser = this;
		let t = "";
		for (let n = 0; n < e.length; n++) {
			let s = e[n];
			if (this.options.extensions?.renderers?.[s.type]) {
				let i = s, o = this.options.extensions.renderers[i.type].call({ parser: this }, i);
				if (o !== !1 || ![
					"space",
					"hr",
					"heading",
					"code",
					"table",
					"blockquote",
					"list",
					"checkbox",
					"html",
					"def",
					"paragraph",
					"text"
				].includes(i.type)) {
					t += o || "";
					continue;
				}
			}
			let r = s;
			switch (r.type) {
				case "space":
					t += this.renderer.space(r);
					break;
				case "hr":
					t += this.renderer.hr(r);
					break;
				case "heading":
					t += this.renderer.heading(r);
					break;
				case "code":
					t += this.renderer.code(r);
					break;
				case "table":
					t += this.renderer.table(r);
					break;
				case "blockquote":
					t += this.renderer.blockquote(r);
					break;
				case "list":
					t += this.renderer.list(r);
					break;
				case "checkbox":
					t += this.renderer.checkbox(r);
					break;
				case "html":
					t += this.renderer.html(r);
					break;
				case "def":
					t += this.renderer.def(r);
					break;
				case "paragraph":
					t += this.renderer.paragraph(r);
					break;
				case "text":
					t += this.renderer.text(r);
					break;
				default: {
					let i = "Token with \"" + r.type + "\" type was not found.";
					if (this.options.silent) return console.error(i), "";
					throw new Error(i);
				}
			}
		}
		return t;
	}
	parseInline(e, t = this.renderer) {
		this.renderer.parser = this;
		let n = "";
		for (let s = 0; s < e.length; s++) {
			let r = e[s];
			if (this.options.extensions?.renderers?.[r.type]) {
				let o = this.options.extensions.renderers[r.type].call({ parser: this }, r);
				if (o !== !1 || ![
					"escape",
					"html",
					"link",
					"image",
					"checkbox",
					"strong",
					"em",
					"codespan",
					"br",
					"del",
					"text"
				].includes(r.type)) {
					n += o || "";
					continue;
				}
			}
			let i = r;
			switch (i.type) {
				case "escape":
					n += t.text(i);
					break;
				case "html":
					n += t.html(i);
					break;
				case "link":
					n += t.link(i);
					break;
				case "image":
					n += t.image(i);
					break;
				case "checkbox":
					n += t.checkbox(i);
					break;
				case "strong":
					n += t.strong(i);
					break;
				case "em":
					n += t.em(i);
					break;
				case "codespan":
					n += t.codespan(i);
					break;
				case "br":
					n += t.br(i);
					break;
				case "del":
					n += t.del(i);
					break;
				case "text":
					n += t.text(i);
					break;
				default: {
					let o = "Token with \"" + i.type + "\" type was not found.";
					if (this.options.silent) return console.error(o), "";
					throw new Error(o);
				}
			}
		}
		return n;
	}
};
var S = class {
	options;
	block;
	constructor(e) {
		this.options = e || R;
	}
	static passThroughHooks = /* @__PURE__ */ new Set([
		"preprocess",
		"postprocess",
		"processAllTokens",
		"emStrongMask"
	]);
	static passThroughHooksRespectAsync = /* @__PURE__ */ new Set([
		"preprocess",
		"postprocess",
		"processAllTokens"
	]);
	preprocess(e) {
		return e;
	}
	postprocess(e) {
		return e;
	}
	processAllTokens(e) {
		return e;
	}
	emStrongMask(e) {
		return e;
	}
	provideLexer(e = this.block) {
		return e ? x.lex : x.lexInline;
	}
	provideParser(e = this.block) {
		return e ? b.parse : b.parseInline;
	}
};
var Z = class {
	defaults = A();
	options = this.setOptions;
	parse = this.parseMarkdown(!0);
	parseInline = this.parseMarkdown(!1);
	Parser = b;
	Renderer = P;
	TextRenderer = L;
	Lexer = x;
	Tokenizer = y;
	Hooks = S;
	constructor(...e) {
		this.use(...e);
	}
	walkTokens(e, t) {
		let n = [];
		for (let s of e) switch (n = n.concat(t.call(this, s)), s.type) {
			case "table": {
				let r = s;
				for (let i of r.header) n = n.concat(this.walkTokens(i.tokens, t));
				for (let i of r.rows) for (let o of i) n = n.concat(this.walkTokens(o.tokens, t));
				break;
			}
			case "list": {
				let r = s;
				n = n.concat(this.walkTokens(r.items, t));
				break;
			}
			default: {
				let r = s;
				this.defaults.extensions?.childTokens?.[r.type] ? this.defaults.extensions.childTokens[r.type].forEach((i) => {
					let o = r[i].flat(1 / 0);
					n = n.concat(this.walkTokens(o, t));
				}) : r.tokens && (n = n.concat(this.walkTokens(r.tokens, t)));
			}
		}
		return n;
	}
	use(...e) {
		let t = this.defaults.extensions || {
			renderers: {},
			childTokens: {}
		};
		return e.forEach((n) => {
			let s = { ...n };
			if (s.async = this.defaults.async || s.async || !1, n.extensions && (n.extensions.forEach((r) => {
				if (!r.name) throw new Error("extension name required");
				if ("renderer" in r) {
					let i = t.renderers[r.name];
					i ? t.renderers[r.name] = function(...o) {
						let u = r.renderer.apply(this, o);
						return u === !1 && (u = i.apply(this, o)), u;
					} : t.renderers[r.name] = r.renderer;
				}
				if ("tokenizer" in r) {
					if (!r.level || r.level !== "block" && r.level !== "inline") throw new Error("extension level must be 'block' or 'inline'");
					let i = t[r.level];
					i ? i.unshift(r.tokenizer) : t[r.level] = [r.tokenizer], r.start && (r.level === "block" ? t.startBlock ? t.startBlock.push(r.start) : t.startBlock = [r.start] : r.level === "inline" && (t.startInline ? t.startInline.push(r.start) : t.startInline = [r.start]));
				}
				"childTokens" in r && r.childTokens && (t.childTokens[r.name] = r.childTokens);
			}), s.extensions = t), n.renderer) {
				let r = this.defaults.renderer || new P(this.defaults);
				for (let i in n.renderer) {
					if (!(i in r)) throw new Error(`renderer '${i}' does not exist`);
					if (["options", "parser"].includes(i)) continue;
					let o = i, u = n.renderer[o], a = r[o];
					r[o] = (...p) => {
						let c = u.apply(r, p);
						return c === !1 && (c = a.apply(r, p)), c || "";
					};
				}
				s.renderer = r;
			}
			if (n.tokenizer) {
				let r = this.defaults.tokenizer || new y(this.defaults);
				for (let i in n.tokenizer) {
					if (!(i in r)) throw new Error(`tokenizer '${i}' does not exist`);
					if ([
						"options",
						"rules",
						"lexer"
					].includes(i)) continue;
					let o = i, u = n.tokenizer[o], a = r[o];
					r[o] = (...p) => {
						let c = u.apply(r, p);
						return c === !1 && (c = a.apply(r, p)), c;
					};
				}
				s.tokenizer = r;
			}
			if (n.hooks) {
				let r = this.defaults.hooks || new S();
				for (let i in n.hooks) {
					if (!(i in r)) throw new Error(`hook '${i}' does not exist`);
					if (["options", "block"].includes(i)) continue;
					let o = i, u = n.hooks[o], a = r[o];
					S.passThroughHooks.has(i) ? r[o] = (p) => {
						if (this.defaults.async && S.passThroughHooksRespectAsync.has(i)) return (async () => {
							let h = await u.call(r, p);
							return a.call(r, h);
						})();
						let c = u.call(r, p);
						return a.call(r, c);
					} : r[o] = (...p) => {
						if (this.defaults.async) return (async () => {
							let h = await u.apply(r, p);
							return h === !1 && (h = await a.apply(r, p)), h;
						})();
						let c = u.apply(r, p);
						return c === !1 && (c = a.apply(r, p)), c;
					};
				}
				s.hooks = r;
			}
			if (n.walkTokens) {
				let r = this.defaults.walkTokens, i = n.walkTokens;
				s.walkTokens = function(o) {
					let u = [];
					return u.push(i.call(this, o)), r && (u = u.concat(r.call(this, o))), u;
				};
			}
			this.defaults = {
				...this.defaults,
				...s
			};
		}), this;
	}
	setOptions(e) {
		return this.defaults = {
			...this.defaults,
			...e
		}, this;
	}
	lexer(e, t) {
		return x.lex(e, t ?? this.defaults);
	}
	parser(e, t) {
		return b.parse(e, t ?? this.defaults);
	}
	parseMarkdown(e) {
		return (n, s) => {
			let r = { ...s }, i = {
				...this.defaults,
				...r
			}, o = this.onError(!!i.silent, !!i.async);
			if (this.defaults.async === !0 && r.async === !1) return o(/* @__PURE__ */ new Error("marked(): The async option was set to true by an extension. Remove async: false from the parse options object to return a Promise."));
			if (typeof n > "u" || n === null) return o(/* @__PURE__ */ new Error("marked(): input parameter is undefined or null"));
			if (typeof n != "string") return o(/* @__PURE__ */ new Error("marked(): input parameter is of type " + Object.prototype.toString.call(n) + ", string expected"));
			if (i.hooks && (i.hooks.options = i, i.hooks.block = e), i.async) return (async () => {
				let u = i.hooks ? await i.hooks.preprocess(n) : n, p = await (i.hooks ? await i.hooks.provideLexer(e) : e ? x.lex : x.lexInline)(u, i), c = i.hooks ? await i.hooks.processAllTokens(p) : p;
				i.walkTokens && await Promise.all(this.walkTokens(c, i.walkTokens));
				let d = await (i.hooks ? await i.hooks.provideParser(e) : e ? b.parse : b.parseInline)(c, i);
				return i.hooks ? await i.hooks.postprocess(d) : d;
			})().catch(o);
			try {
				i.hooks && (n = i.hooks.preprocess(n));
				let a = (i.hooks ? i.hooks.provideLexer(e) : e ? x.lex : x.lexInline)(n, i);
				i.hooks && (a = i.hooks.processAllTokens(a)), i.walkTokens && this.walkTokens(a, i.walkTokens);
				let c = (i.hooks ? i.hooks.provideParser(e) : e ? b.parse : b.parseInline)(a, i);
				return i.hooks && (c = i.hooks.postprocess(c)), c;
			} catch (u) {
				return o(u);
			}
		};
	}
	onError(e, t) {
		return (n) => {
			if (n.message += `
Please report this to https://github.com/markedjs/marked.`, e) {
				let s = "<p>An error occurred:</p><pre>" + T(n.message + "", !0) + "</pre>";
				return t ? Promise.resolve(s) : s;
			}
			if (t) return Promise.reject(n);
			throw n;
		};
	}
};
var M = new Z();
function f(l, e) {
	return M.parse(l, e);
}
f.options = f.setOptions = function(l) {
	return M.setOptions(l), f.defaults = M.defaults, j(f.defaults), f;
};
f.getDefaults = A;
f.defaults = R;
function dt(...l) {
	return M.use(...l), f.defaults = M.defaults, j(f.defaults), f;
}
f.use = dt;
f.walkTokens = function(l, e) {
	return M.walkTokens(l, e);
};
f.parseInline = M.parseInline;
f.Parser = b;
f.parser = b.parse;
f.Renderer = P;
f.TextRenderer = L;
f.Lexer = x;
f.lexer = x.lex;
f.Tokenizer = y;
f.Hooks = S;
f.parse = f;
f.options;
f.setOptions;
f.walkTokens;
f.parseInline;
b.parse;
x.lex;
//#endregion
//#region node_modules/shiki/dist/rolldown-runtime-BBjsoOtd.mjs
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __exportAll = (all, no_symbols) => {
	let target = {};
	for (var name in all) __defProp(target, name, {
		get: all[name],
		enumerable: true
	});
	if (!no_symbols) __defProp(target, Symbol.toStringTag, { value: "Module" });
	return target;
};
var __copyProps = (to, from, except, desc) => {
	if (from && typeof from === "object" || typeof from === "function") for (var keys = __getOwnPropNames(from), i = 0, n = keys.length, key; i < n; i++) {
		key = keys[i];
		if (!__hasOwnProp.call(to, key) && key !== except) __defProp(to, key, {
			get: ((k) => from[k]).bind(null, key),
			enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable
		});
	}
	return to;
};
var __reExport = (target, mod, secondTarget) => (__copyProps(target, mod, "default"), secondTarget && __copyProps(secondTarget, mod, "default"));
//#endregion
//#region node_modules/shiki/dist/langs-bundle-full-xQVO1Cek.mjs
var bundledLanguagesInfo = [
	{
		"id": "abap",
		"name": "ABAP",
		"import": (() => import("@shikijs/langs/abap"))
	},
	{
		"id": "actionscript-3",
		"name": "ActionScript",
		"aliases": ["actionscript", "as3"],
		"import": (() => import("@shikijs/langs/actionscript-3"))
	},
	{
		"id": "ada",
		"name": "Ada",
		"import": (() => import("@shikijs/langs/ada"))
	},
	{
		"id": "ahk",
		"name": "AutoHotkey",
		"aliases": ["ahk1"],
		"import": (() => import("@shikijs/langs/ahk"))
	},
	{
		"id": "ahk2",
		"name": "AutoHotkey2",
		"import": (() => import("@shikijs/langs/ahk2"))
	},
	{
		"id": "angular-html",
		"name": "Angular HTML",
		"import": (() => import("@shikijs/langs/angular-html"))
	},
	{
		"id": "angular-ts",
		"name": "Angular TypeScript",
		"import": (() => import("@shikijs/langs/angular-ts"))
	},
	{
		"id": "apache",
		"name": "Apache Conf",
		"import": (() => import("@shikijs/langs/apache"))
	},
	{
		"id": "apex",
		"name": "Apex",
		"import": (() => import("@shikijs/langs/apex"))
	},
	{
		"id": "apl",
		"name": "APL",
		"import": (() => import("@shikijs/langs/apl"))
	},
	{
		"id": "applescript",
		"name": "AppleScript",
		"import": (() => import("@shikijs/langs/applescript"))
	},
	{
		"id": "ara",
		"name": "Ara",
		"import": (() => import("@shikijs/langs/ara"))
	},
	{
		"id": "asciidoc",
		"name": "AsciiDoc",
		"aliases": ["adoc"],
		"import": (() => import("@shikijs/langs/asciidoc"))
	},
	{
		"id": "asm",
		"name": "Assembly",
		"import": (() => import("@shikijs/langs/asm"))
	},
	{
		"id": "astro",
		"name": "Astro",
		"import": (() => import("@shikijs/langs/astro"))
	},
	{
		"id": "awk",
		"name": "AWK",
		"import": (() => import("@shikijs/langs/awk"))
	},
	{
		"id": "ballerina",
		"name": "Ballerina",
		"import": (() => import("@shikijs/langs/ballerina"))
	},
	{
		"id": "bat",
		"name": "Batch File",
		"aliases": ["batch", "cmd"],
		"import": (() => import("@shikijs/langs/bat"))
	},
	{
		"id": "beancount",
		"name": "Beancount",
		"import": (() => import("@shikijs/langs/beancount"))
	},
	{
		"id": "berry",
		"name": "Berry",
		"aliases": ["be"],
		"import": (() => import("@shikijs/langs/berry"))
	},
	{
		"id": "bibtex",
		"name": "BibTeX",
		"import": (() => import("@shikijs/langs/bibtex"))
	},
	{
		"id": "bicep",
		"name": "Bicep",
		"import": (() => import("@shikijs/langs/bicep"))
	},
	{
		"id": "bird2",
		"name": "BIRD2 Configuration",
		"aliases": ["bird"],
		"import": (() => import("@shikijs/langs/bird2"))
	},
	{
		"id": "blade",
		"name": "Blade",
		"import": (() => import("@shikijs/langs/blade"))
	},
	{
		"id": "bsl",
		"name": "1C (Enterprise)",
		"aliases": ["1c"],
		"import": (() => import("@shikijs/langs/bsl"))
	},
	{
		"id": "c",
		"name": "C",
		"import": (() => import("@shikijs/langs/c"))
	},
	{
		"id": "c3",
		"name": "C3",
		"import": (() => import("@shikijs/langs/c3"))
	},
	{
		"id": "cadence",
		"name": "Cadence",
		"aliases": ["cdc"],
		"import": (() => import("@shikijs/langs/cadence"))
	},
	{
		"id": "cairo",
		"name": "Cairo",
		"import": (() => import("@shikijs/langs/cairo"))
	},
	{
		"id": "chapel",
		"name": "Chapel",
		"aliases": ["chpl"],
		"import": (() => import("@shikijs/langs/chapel"))
	},
	{
		"id": "clarity",
		"name": "Clarity",
		"import": (() => import("@shikijs/langs/clarity"))
	},
	{
		"id": "clojure",
		"name": "Clojure",
		"aliases": ["clj"],
		"import": (() => import("@shikijs/langs/clojure"))
	},
	{
		"id": "cmake",
		"name": "CMake",
		"import": (() => import("@shikijs/langs/cmake"))
	},
	{
		"id": "cobol",
		"name": "COBOL",
		"import": (() => import("@shikijs/langs/cobol"))
	},
	{
		"id": "codeowners",
		"name": "CODEOWNERS",
		"import": (() => import("@shikijs/langs/codeowners"))
	},
	{
		"id": "codeql",
		"name": "CodeQL",
		"aliases": ["ql"],
		"import": (() => import("@shikijs/langs/codeql"))
	},
	{
		"id": "coffee",
		"name": "CoffeeScript",
		"aliases": ["coffeescript"],
		"import": (() => import("@shikijs/langs/coffee"))
	},
	{
		"id": "common-lisp",
		"name": "Common Lisp",
		"aliases": ["lisp"],
		"import": (() => import("@shikijs/langs/common-lisp"))
	},
	{
		"id": "coq",
		"name": "Rocq",
		"import": (() => import("@shikijs/langs/coq"))
	},
	{
		"id": "cpp",
		"name": "C++",
		"aliases": ["c++"],
		"import": (() => import("@shikijs/langs/cpp"))
	},
	{
		"id": "crystal",
		"name": "Crystal",
		"import": (() => import("@shikijs/langs/crystal"))
	},
	{
		"id": "csharp",
		"name": "C#",
		"aliases": ["c#", "cs"],
		"import": (() => import("@shikijs/langs/csharp"))
	},
	{
		"id": "css",
		"name": "CSS",
		"import": (() => import("@shikijs/langs/css"))
	},
	{
		"id": "csv",
		"name": "CSV",
		"import": (() => import("@shikijs/langs/csv"))
	},
	{
		"id": "cue",
		"name": "CUE",
		"import": (() => import("@shikijs/langs/cue"))
	},
	{
		"id": "cypher",
		"name": "Cypher",
		"aliases": ["cql"],
		"import": (() => import("@shikijs/langs/cypher"))
	},
	{
		"id": "d",
		"name": "D",
		"import": (() => import("@shikijs/langs/d"))
	},
	{
		"id": "dart",
		"name": "Dart",
		"import": (() => import("@shikijs/langs/dart"))
	},
	{
		"id": "dax",
		"name": "DAX",
		"import": (() => import("@shikijs/langs/dax"))
	},
	{
		"id": "desktop",
		"name": "Desktop",
		"import": (() => import("@shikijs/langs/desktop"))
	},
	{
		"id": "diff",
		"name": "Diff",
		"import": (() => import("@shikijs/langs/diff"))
	},
	{
		"id": "docker",
		"name": "Dockerfile",
		"aliases": ["dockerfile"],
		"import": (() => import("@shikijs/langs/docker"))
	},
	{
		"id": "dotenv",
		"name": "dotEnv",
		"import": (() => import("@shikijs/langs/dotenv"))
	},
	{
		"id": "dream-maker",
		"name": "Dream Maker",
		"import": (() => import("@shikijs/langs/dream-maker"))
	},
	{
		"id": "edge",
		"name": "Edge",
		"import": (() => import("@shikijs/langs/edge"))
	},
	{
		"id": "elixir",
		"name": "Elixir",
		"import": (() => import("@shikijs/langs/elixir"))
	},
	{
		"id": "elm",
		"name": "Elm",
		"import": (() => import("@shikijs/langs/elm"))
	},
	{
		"id": "emacs-lisp",
		"name": "Emacs Lisp",
		"aliases": ["elisp"],
		"import": (() => import("@shikijs/langs/emacs-lisp"))
	},
	{
		"id": "erb",
		"name": "ERB",
		"import": (() => import("@shikijs/langs/erb"))
	},
	{
		"id": "erlang",
		"name": "Erlang",
		"aliases": ["erl"],
		"import": (() => import("@shikijs/langs/erlang"))
	},
	{
		"id": "fennel",
		"name": "Fennel",
		"import": (() => import("@shikijs/langs/fennel"))
	},
	{
		"id": "fish",
		"name": "Fish",
		"import": (() => import("@shikijs/langs/fish"))
	},
	{
		"id": "fluent",
		"name": "Fluent",
		"aliases": ["ftl"],
		"import": (() => import("@shikijs/langs/fluent"))
	},
	{
		"id": "fortran-fixed-form",
		"name": "Fortran (Fixed Form)",
		"aliases": [
			"f",
			"for",
			"f77"
		],
		"import": (() => import("@shikijs/langs/fortran-fixed-form"))
	},
	{
		"id": "fortran-free-form",
		"name": "Fortran (Free Form)",
		"aliases": [
			"f90",
			"f95",
			"f03",
			"f08",
			"f18"
		],
		"import": (() => import("@shikijs/langs/fortran-free-form"))
	},
	{
		"id": "fsharp",
		"name": "F#",
		"aliases": ["f#", "fs"],
		"import": (() => import("@shikijs/langs/fsharp"))
	},
	{
		"id": "gdresource",
		"name": "GDResource",
		"aliases": ["tscn", "tres"],
		"import": (() => import("@shikijs/langs/gdresource"))
	},
	{
		"id": "gdscript",
		"name": "GDScript",
		"aliases": ["gd"],
		"import": (() => import("@shikijs/langs/gdscript"))
	},
	{
		"id": "gdshader",
		"name": "GDShader",
		"import": (() => import("@shikijs/langs/gdshader"))
	},
	{
		"id": "genie",
		"name": "Genie",
		"import": (() => import("@shikijs/langs/genie"))
	},
	{
		"id": "gherkin",
		"name": "Gherkin",
		"import": (() => import("@shikijs/langs/gherkin"))
	},
	{
		"id": "git-commit",
		"name": "Git Commit Message",
		"import": (() => import("@shikijs/langs/git-commit"))
	},
	{
		"id": "git-rebase",
		"name": "Git Rebase Message",
		"import": (() => import("@shikijs/langs/git-rebase"))
	},
	{
		"id": "gleam",
		"name": "Gleam",
		"import": (() => import("@shikijs/langs/gleam"))
	},
	{
		"id": "glimmer-js",
		"name": "Glimmer JS",
		"aliases": ["gjs"],
		"import": (() => import("@shikijs/langs/glimmer-js"))
	},
	{
		"id": "glimmer-ts",
		"name": "Glimmer TS",
		"aliases": ["gts"],
		"import": (() => import("@shikijs/langs/glimmer-ts"))
	},
	{
		"id": "glsl",
		"name": "GLSL",
		"import": (() => import("@shikijs/langs/glsl"))
	},
	{
		"id": "gn",
		"name": "GN",
		"import": (() => import("@shikijs/langs/gn"))
	},
	{
		"id": "gnuplot",
		"name": "Gnuplot",
		"import": (() => import("@shikijs/langs/gnuplot"))
	},
	{
		"id": "go",
		"name": "Go",
		"import": (() => import("@shikijs/langs/go"))
	},
	{
		"id": "graphql",
		"name": "GraphQL",
		"aliases": ["gql"],
		"import": (() => import("@shikijs/langs/graphql"))
	},
	{
		"id": "groovy",
		"name": "Groovy",
		"import": (() => import("@shikijs/langs/groovy"))
	},
	{
		"id": "hack",
		"name": "Hack",
		"import": (() => import("@shikijs/langs/hack"))
	},
	{
		"id": "haml",
		"name": "Ruby Haml",
		"import": (() => import("@shikijs/langs/haml"))
	},
	{
		"id": "handlebars",
		"name": "Handlebars",
		"aliases": ["hbs"],
		"import": (() => import("@shikijs/langs/handlebars"))
	},
	{
		"id": "haskell",
		"name": "Haskell",
		"aliases": ["hs"],
		"import": (() => import("@shikijs/langs/haskell"))
	},
	{
		"id": "haxe",
		"name": "Haxe",
		"import": (() => import("@shikijs/langs/haxe"))
	},
	{
		"id": "hcl",
		"name": "HashiCorp HCL",
		"import": (() => import("@shikijs/langs/hcl"))
	},
	{
		"id": "hjson",
		"name": "Hjson",
		"import": (() => import("@shikijs/langs/hjson"))
	},
	{
		"id": "hlsl",
		"name": "HLSL",
		"import": (() => import("@shikijs/langs/hlsl"))
	},
	{
		"id": "html",
		"name": "HTML",
		"import": (() => import("@shikijs/langs/html"))
	},
	{
		"id": "html-derivative",
		"name": "HTML (Derivative)",
		"import": (() => import("@shikijs/langs/html-derivative"))
	},
	{
		"id": "http",
		"name": "HTTP",
		"import": (() => import("@shikijs/langs/http"))
	},
	{
		"id": "hurl",
		"name": "Hurl",
		"import": (() => import("@shikijs/langs/hurl"))
	},
	{
		"id": "hxml",
		"name": "HXML",
		"import": (() => import("@shikijs/langs/hxml"))
	},
	{
		"id": "hy",
		"name": "Hy",
		"import": (() => import("@shikijs/langs/hy"))
	},
	{
		"id": "imba",
		"name": "Imba",
		"import": (() => import("@shikijs/langs/imba"))
	},
	{
		"id": "ini",
		"name": "INI",
		"aliases": ["properties"],
		"import": (() => import("@shikijs/langs/ini"))
	},
	{
		"id": "java",
		"name": "Java",
		"import": (() => import("@shikijs/langs/java"))
	},
	{
		"id": "javascript",
		"name": "JavaScript",
		"aliases": [
			"js",
			"cjs",
			"mjs"
		],
		"import": (() => import("@shikijs/langs/javascript"))
	},
	{
		"id": "jinja",
		"name": "Jinja",
		"import": (() => import("@shikijs/langs/jinja"))
	},
	{
		"id": "jison",
		"name": "Jison",
		"import": (() => import("@shikijs/langs/jison"))
	},
	{
		"id": "json",
		"name": "JSON",
		"import": (() => import("@shikijs/langs/json"))
	},
	{
		"id": "json5",
		"name": "JSON5",
		"import": (() => import("@shikijs/langs/json5"))
	},
	{
		"id": "jsonc",
		"name": "JSON with Comments",
		"import": (() => import("@shikijs/langs/jsonc"))
	},
	{
		"id": "jsonl",
		"name": "JSON Lines",
		"import": (() => import("@shikijs/langs/jsonl"))
	},
	{
		"id": "jsonnet",
		"name": "Jsonnet",
		"import": (() => import("@shikijs/langs/jsonnet"))
	},
	{
		"id": "jssm",
		"name": "JSSM",
		"aliases": ["fsl"],
		"import": (() => import("@shikijs/langs/jssm"))
	},
	{
		"id": "jsx",
		"name": "JSX",
		"import": (() => import("@shikijs/langs/jsx"))
	},
	{
		"id": "julia",
		"name": "Julia",
		"aliases": ["jl"],
		"import": (() => import("@shikijs/langs/julia"))
	},
	{
		"id": "just",
		"name": "Just",
		"aliases": ["justfile"],
		"import": (() => import("@shikijs/langs/just"))
	},
	{
		"id": "kdl",
		"name": "KDL",
		"import": (() => import("@shikijs/langs/kdl"))
	},
	{
		"id": "kotlin",
		"name": "Kotlin",
		"aliases": ["kt", "kts"],
		"import": (() => import("@shikijs/langs/kotlin"))
	},
	{
		"id": "kusto",
		"name": "Kusto",
		"aliases": ["kql"],
		"import": (() => import("@shikijs/langs/kusto"))
	},
	{
		"id": "latex",
		"name": "LaTeX",
		"import": (() => import("@shikijs/langs/latex"))
	},
	{
		"id": "lean",
		"name": "Lean 4",
		"aliases": ["lean4"],
		"import": (() => import("@shikijs/langs/lean"))
	},
	{
		"id": "less",
		"name": "Less",
		"import": (() => import("@shikijs/langs/less"))
	},
	{
		"id": "liquid",
		"name": "Liquid",
		"import": (() => import("@shikijs/langs/liquid"))
	},
	{
		"id": "llvm",
		"name": "LLVM IR",
		"import": (() => import("@shikijs/langs/llvm"))
	},
	{
		"id": "log",
		"name": "Log file",
		"import": (() => import("@shikijs/langs/log"))
	},
	{
		"id": "logo",
		"name": "Logo",
		"import": (() => import("@shikijs/langs/logo"))
	},
	{
		"id": "lua",
		"name": "Lua",
		"import": (() => import("@shikijs/langs/lua"))
	},
	{
		"id": "luau",
		"name": "Luau",
		"import": (() => import("@shikijs/langs/luau"))
	},
	{
		"id": "make",
		"name": "Makefile",
		"aliases": ["makefile"],
		"import": (() => import("@shikijs/langs/make"))
	},
	{
		"id": "markdown",
		"name": "Markdown",
		"aliases": ["md"],
		"import": (() => import("@shikijs/langs/markdown"))
	},
	{
		"id": "marko",
		"name": "Marko",
		"import": (() => import("@shikijs/langs/marko"))
	},
	{
		"id": "matlab",
		"name": "MATLAB",
		"import": (() => import("@shikijs/langs/matlab"))
	},
	{
		"id": "mdc",
		"name": "MDC",
		"import": (() => import("@shikijs/langs/mdc"))
	},
	{
		"id": "mdx",
		"name": "MDX",
		"import": (() => import("@shikijs/langs/mdx"))
	},
	{
		"id": "mermaid",
		"name": "Mermaid",
		"aliases": ["mmd"],
		"import": (() => import("@shikijs/langs/mermaid"))
	},
	{
		"id": "mipsasm",
		"name": "MIPS Assembly",
		"aliases": ["mips"],
		"import": (() => import("@shikijs/langs/mipsasm"))
	},
	{
		"id": "mojo",
		"name": "Mojo",
		"import": (() => import("@shikijs/langs/mojo"))
	},
	{
		"id": "moonbit",
		"name": "MoonBit",
		"aliases": ["mbt", "mbti"],
		"import": (() => import("@shikijs/langs/moonbit"))
	},
	{
		"id": "move",
		"name": "Move",
		"import": (() => import("@shikijs/langs/move"))
	},
	{
		"id": "narrat",
		"name": "Narrat Language",
		"aliases": ["nar"],
		"import": (() => import("@shikijs/langs/narrat"))
	},
	{
		"id": "nextflow",
		"name": "Nextflow",
		"aliases": ["nf"],
		"import": (() => import("@shikijs/langs/nextflow"))
	},
	{
		"id": "nextflow-groovy",
		"name": "Nextflow Groovy",
		"import": (() => import("@shikijs/langs/nextflow-groovy"))
	},
	{
		"id": "nginx",
		"name": "Nginx",
		"import": (() => import("@shikijs/langs/nginx"))
	},
	{
		"id": "nim",
		"name": "Nim",
		"import": (() => import("@shikijs/langs/nim"))
	},
	{
		"id": "nix",
		"name": "Nix",
		"import": (() => import("@shikijs/langs/nix"))
	},
	{
		"id": "nsis",
		"name": "NSIS",
		"import": (() => import("@shikijs/langs/nsis"))
	},
	{
		"id": "nushell",
		"name": "nushell",
		"aliases": ["nu"],
		"import": (() => import("@shikijs/langs/nushell"))
	},
	{
		"id": "objective-c",
		"name": "Objective-C",
		"aliases": ["objc"],
		"import": (() => import("@shikijs/langs/objective-c"))
	},
	{
		"id": "objective-cpp",
		"name": "Objective-C++",
		"import": (() => import("@shikijs/langs/objective-cpp"))
	},
	{
		"id": "ocaml",
		"name": "OCaml",
		"import": (() => import("@shikijs/langs/ocaml"))
	},
	{
		"id": "odin",
		"name": "Odin",
		"import": (() => import("@shikijs/langs/odin"))
	},
	{
		"id": "openscad",
		"name": "OpenSCAD",
		"aliases": ["scad"],
		"import": (() => import("@shikijs/langs/openscad"))
	},
	{
		"id": "org",
		"name": "Org Markup",
		"import": (() => import("@shikijs/langs/org"))
	},
	{
		"id": "pascal",
		"name": "Pascal",
		"import": (() => import("@shikijs/langs/pascal"))
	},
	{
		"id": "perl",
		"name": "Perl",
		"import": (() => import("@shikijs/langs/perl"))
	},
	{
		"id": "php",
		"name": "PHP",
		"import": (() => import("@shikijs/langs/php"))
	},
	{
		"id": "pkl",
		"name": "Pkl",
		"import": (() => import("@shikijs/langs/pkl"))
	},
	{
		"id": "plsql",
		"name": "PL/SQL",
		"import": (() => import("@shikijs/langs/plsql"))
	},
	{
		"id": "po",
		"name": "Gettext PO",
		"aliases": ["pot", "potx"],
		"import": (() => import("@shikijs/langs/po"))
	},
	{
		"id": "polar",
		"name": "Polar",
		"import": (() => import("@shikijs/langs/polar"))
	},
	{
		"id": "postcss",
		"name": "PostCSS",
		"import": (() => import("@shikijs/langs/postcss"))
	},
	{
		"id": "powerquery",
		"name": "PowerQuery",
		"import": (() => import("@shikijs/langs/powerquery"))
	},
	{
		"id": "powershell",
		"name": "PowerShell",
		"aliases": [
			"ps",
			"ps1",
			"pwsh"
		],
		"import": (() => import("@shikijs/langs/powershell"))
	},
	{
		"id": "prisma",
		"name": "Prisma",
		"import": (() => import("@shikijs/langs/prisma"))
	},
	{
		"id": "prolog",
		"name": "Prolog",
		"import": (() => import("@shikijs/langs/prolog"))
	},
	{
		"id": "proto",
		"name": "Protocol Buffer 3",
		"aliases": ["protobuf"],
		"import": (() => import("@shikijs/langs/proto"))
	},
	{
		"id": "pug",
		"name": "Pug",
		"aliases": ["jade"],
		"import": (() => import("@shikijs/langs/pug"))
	},
	{
		"id": "puppet",
		"name": "Puppet",
		"import": (() => import("@shikijs/langs/puppet"))
	},
	{
		"id": "purescript",
		"name": "PureScript",
		"import": (() => import("@shikijs/langs/purescript"))
	},
	{
		"id": "python",
		"name": "Python",
		"aliases": ["py"],
		"import": (() => import("@shikijs/langs/python"))
	},
	{
		"id": "qml",
		"name": "QML",
		"import": (() => import("@shikijs/langs/qml"))
	},
	{
		"id": "qmldir",
		"name": "QML Directory",
		"import": (() => import("@shikijs/langs/qmldir"))
	},
	{
		"id": "qss",
		"name": "Qt Style Sheets",
		"import": (() => import("@shikijs/langs/qss"))
	},
	{
		"id": "r",
		"name": "R",
		"import": (() => import("@shikijs/langs/r"))
	},
	{
		"id": "racket",
		"name": "Racket",
		"import": (() => import("@shikijs/langs/racket"))
	},
	{
		"id": "raku",
		"name": "Raku",
		"aliases": ["perl6"],
		"import": (() => import("@shikijs/langs/raku"))
	},
	{
		"id": "razor",
		"name": "ASP.NET Razor",
		"import": (() => import("@shikijs/langs/razor"))
	},
	{
		"id": "rbs",
		"name": "RBS",
		"aliases": ["ruby-signature"],
		"import": (() => import("@shikijs/langs/rbs"))
	},
	{
		"id": "reg",
		"name": "Windows Registry Script",
		"import": (() => import("@shikijs/langs/reg"))
	},
	{
		"id": "regexp",
		"name": "RegExp",
		"aliases": ["regex"],
		"import": (() => import("@shikijs/langs/regexp"))
	},
	{
		"id": "rel",
		"name": "Rel",
		"import": (() => import("@shikijs/langs/rel"))
	},
	{
		"id": "riscv",
		"name": "RISC-V",
		"import": (() => import("@shikijs/langs/riscv"))
	},
	{
		"id": "ron",
		"name": "RON",
		"import": (() => import("@shikijs/langs/ron"))
	},
	{
		"id": "rosmsg",
		"name": "ROS Interface",
		"import": (() => import("@shikijs/langs/rosmsg"))
	},
	{
		"id": "rst",
		"name": "reStructuredText",
		"import": (() => import("@shikijs/langs/rst"))
	},
	{
		"id": "ruby",
		"name": "Ruby",
		"aliases": ["rb"],
		"import": (() => import("@shikijs/langs/ruby"))
	},
	{
		"id": "rust",
		"name": "Rust",
		"aliases": ["rs"],
		"import": (() => import("@shikijs/langs/rust"))
	},
	{
		"id": "sas",
		"name": "SAS",
		"import": (() => import("@shikijs/langs/sas"))
	},
	{
		"id": "sass",
		"name": "Sass",
		"import": (() => import("@shikijs/langs/sass"))
	},
	{
		"id": "scala",
		"name": "Scala",
		"import": (() => import("@shikijs/langs/scala"))
	},
	{
		"id": "scheme",
		"name": "Scheme",
		"import": (() => import("@shikijs/langs/scheme"))
	},
	{
		"id": "scss",
		"name": "SCSS",
		"import": (() => import("@shikijs/langs/scss"))
	},
	{
		"id": "sdbl",
		"name": "1C (Query)",
		"aliases": ["1c-query"],
		"import": (() => import("@shikijs/langs/sdbl"))
	},
	{
		"id": "shaderlab",
		"name": "ShaderLab",
		"aliases": ["shader"],
		"import": (() => import("@shikijs/langs/shaderlab"))
	},
	{
		"id": "shellscript",
		"name": "Shell",
		"aliases": [
			"bash",
			"sh",
			"shell",
			"zsh"
		],
		"import": (() => import("@shikijs/langs/shellscript"))
	},
	{
		"id": "shellsession",
		"name": "Shell Session",
		"aliases": ["console"],
		"import": (() => import("@shikijs/langs/shellsession"))
	},
	{
		"id": "smalltalk",
		"name": "GNU Smalltalk",
		"import": (() => import("@shikijs/langs/smalltalk"))
	},
	{
		"id": "smithy",
		"name": "Smithy",
		"import": (() => import("@shikijs/langs/smithy"))
	},
	{
		"id": "solidity",
		"name": "Solidity",
		"import": (() => import("@shikijs/langs/solidity"))
	},
	{
		"id": "soy",
		"name": "Closure Templates",
		"aliases": ["closure-templates"],
		"import": (() => import("@shikijs/langs/soy"))
	},
	{
		"id": "sparql",
		"name": "SPARQL",
		"import": (() => import("@shikijs/langs/sparql"))
	},
	{
		"id": "splunk",
		"name": "Splunk Query Language",
		"aliases": ["spl"],
		"import": (() => import("@shikijs/langs/splunk"))
	},
	{
		"id": "sql",
		"name": "SQL",
		"import": (() => import("@shikijs/langs/sql"))
	},
	{
		"id": "ssh-config",
		"name": "SSH Config",
		"import": (() => import("@shikijs/langs/ssh-config"))
	},
	{
		"id": "stata",
		"name": "Stata",
		"import": (() => import("@shikijs/langs/stata"))
	},
	{
		"id": "stylus",
		"name": "Stylus",
		"aliases": ["styl"],
		"import": (() => import("@shikijs/langs/stylus"))
	},
	{
		"id": "surrealql",
		"name": "SurrealQL",
		"aliases": ["surql"],
		"import": (() => import("@shikijs/langs/surrealql"))
	},
	{
		"id": "svelte",
		"name": "Svelte",
		"import": (() => import("@shikijs/langs/svelte"))
	},
	{
		"id": "swift",
		"name": "Swift",
		"import": (() => import("@shikijs/langs/swift"))
	},
	{
		"id": "system-verilog",
		"name": "SystemVerilog",
		"import": (() => import("@shikijs/langs/system-verilog"))
	},
	{
		"id": "systemd",
		"name": "Systemd Units",
		"import": (() => import("@shikijs/langs/systemd"))
	},
	{
		"id": "talonscript",
		"name": "TalonScript",
		"aliases": ["talon"],
		"import": (() => import("@shikijs/langs/talonscript"))
	},
	{
		"id": "tasl",
		"name": "Tasl",
		"import": (() => import("@shikijs/langs/tasl"))
	},
	{
		"id": "tcl",
		"name": "Tcl",
		"import": (() => import("@shikijs/langs/tcl"))
	},
	{
		"id": "templ",
		"name": "Templ",
		"import": (() => import("@shikijs/langs/templ"))
	},
	{
		"id": "terraform",
		"name": "Terraform",
		"aliases": ["tf", "tfvars"],
		"import": (() => import("@shikijs/langs/terraform"))
	},
	{
		"id": "tex",
		"name": "TeX",
		"import": (() => import("@shikijs/langs/tex"))
	},
	{
		"id": "toml",
		"name": "TOML",
		"import": (() => import("@shikijs/langs/toml"))
	},
	{
		"id": "ts-tags",
		"name": "TypeScript with Tags",
		"aliases": ["lit"],
		"import": (() => import("@shikijs/langs/ts-tags"))
	},
	{
		"id": "tsv",
		"name": "TSV",
		"import": (() => import("@shikijs/langs/tsv"))
	},
	{
		"id": "tsx",
		"name": "TSX",
		"import": (() => import("@shikijs/langs/tsx"))
	},
	{
		"id": "turtle",
		"name": "Turtle",
		"import": (() => import("@shikijs/langs/turtle"))
	},
	{
		"id": "twig",
		"name": "Twig",
		"import": (() => import("@shikijs/langs/twig"))
	},
	{
		"id": "typescript",
		"name": "TypeScript",
		"aliases": [
			"ts",
			"cts",
			"mts"
		],
		"import": (() => import("@shikijs/langs/typescript"))
	},
	{
		"id": "typespec",
		"name": "TypeSpec",
		"aliases": ["tsp"],
		"import": (() => import("@shikijs/langs/typespec"))
	},
	{
		"id": "typst",
		"name": "Typst",
		"aliases": ["typ"],
		"import": (() => import("@shikijs/langs/typst"))
	},
	{
		"id": "v",
		"name": "V",
		"import": (() => import("@shikijs/langs/v"))
	},
	{
		"id": "vala",
		"name": "Vala",
		"import": (() => import("@shikijs/langs/vala"))
	},
	{
		"id": "vb",
		"name": "Visual Basic",
		"import": (() => import("@shikijs/langs/vb"))
	},
	{
		"id": "verilog",
		"name": "Verilog",
		"import": (() => import("@shikijs/langs/verilog"))
	},
	{
		"id": "vhdl",
		"name": "VHDL",
		"import": (() => import("@shikijs/langs/vhdl"))
	},
	{
		"id": "viml",
		"name": "Vim Script",
		"aliases": ["vim", "vimscript"],
		"import": (() => import("@shikijs/langs/viml"))
	},
	{
		"id": "vue",
		"name": "Vue",
		"import": (() => import("@shikijs/langs/vue"))
	},
	{
		"id": "vue-html",
		"name": "Vue HTML",
		"import": (() => import("@shikijs/langs/vue-html"))
	},
	{
		"id": "vue-vine",
		"name": "Vue Vine",
		"import": (() => import("@shikijs/langs/vue-vine"))
	},
	{
		"id": "vyper",
		"name": "Vyper",
		"aliases": ["vy"],
		"import": (() => import("@shikijs/langs/vyper"))
	},
	{
		"id": "wasm",
		"name": "WebAssembly",
		"import": (() => import("@shikijs/langs/wasm"))
	},
	{
		"id": "wenyan",
		"name": "Wenyan",
		"aliases": ["文言"],
		"import": (() => import("@shikijs/langs/wenyan"))
	},
	{
		"id": "wgsl",
		"name": "WGSL",
		"import": (() => import("@shikijs/langs/wgsl"))
	},
	{
		"id": "wikitext",
		"name": "Wikitext",
		"aliases": ["mediawiki", "wiki"],
		"import": (() => import("@shikijs/langs/wikitext"))
	},
	{
		"id": "wit",
		"name": "WebAssembly Interface Types",
		"import": (() => import("@shikijs/langs/wit"))
	},
	{
		"id": "wolfram",
		"name": "Wolfram",
		"aliases": ["wl"],
		"import": (() => import("@shikijs/langs/wolfram"))
	},
	{
		"id": "xml",
		"name": "XML",
		"import": (() => import("@shikijs/langs/xml"))
	},
	{
		"id": "xsl",
		"name": "XSL",
		"import": (() => import("@shikijs/langs/xsl"))
	},
	{
		"id": "yaml",
		"name": "YAML",
		"aliases": ["yml"],
		"import": (() => import("@shikijs/langs/yaml"))
	},
	{
		"id": "zenscript",
		"name": "ZenScript",
		"import": (() => import("@shikijs/langs/zenscript"))
	},
	{
		"id": "zig",
		"name": "Zig",
		"import": (() => import("@shikijs/langs/zig"))
	}
];
var bundledLanguagesBase = Object.fromEntries(bundledLanguagesInfo.map((i) => [i.id, i.import]));
var bundledLanguagesAlias = Object.fromEntries(bundledLanguagesInfo.flatMap((i) => i.aliases?.map((a) => [a, i.import]) || []));
var bundledLanguages = {
	...bundledLanguagesBase,
	...bundledLanguagesAlias
};
var bundledThemes = Object.fromEntries([
	{
		"id": "andromeeda",
		"displayName": "Andromeeda",
		"type": "dark",
		"import": (() => import("@shikijs/themes/andromeeda"))
	},
	{
		"id": "aurora-x",
		"displayName": "Aurora X",
		"type": "dark",
		"import": (() => import("@shikijs/themes/aurora-x"))
	},
	{
		"id": "ayu-dark",
		"displayName": "Ayu Dark",
		"type": "dark",
		"import": (() => import("@shikijs/themes/ayu-dark"))
	},
	{
		"id": "ayu-light",
		"displayName": "Ayu Light",
		"type": "light",
		"import": (() => import("@shikijs/themes/ayu-light"))
	},
	{
		"id": "ayu-mirage",
		"displayName": "Ayu Mirage",
		"type": "dark",
		"import": (() => import("@shikijs/themes/ayu-mirage"))
	},
	{
		"id": "catppuccin-frappe",
		"displayName": "Catppuccin Frappé",
		"type": "dark",
		"import": (() => import("@shikijs/themes/catppuccin-frappe"))
	},
	{
		"id": "catppuccin-latte",
		"displayName": "Catppuccin Latte",
		"type": "light",
		"import": (() => import("@shikijs/themes/catppuccin-latte"))
	},
	{
		"id": "catppuccin-macchiato",
		"displayName": "Catppuccin Macchiato",
		"type": "dark",
		"import": (() => import("@shikijs/themes/catppuccin-macchiato"))
	},
	{
		"id": "catppuccin-mocha",
		"displayName": "Catppuccin Mocha",
		"type": "dark",
		"import": (() => import("@shikijs/themes/catppuccin-mocha"))
	},
	{
		"id": "dark-plus",
		"displayName": "Dark Plus",
		"type": "dark",
		"import": (() => import("@shikijs/themes/dark-plus"))
	},
	{
		"id": "dracula",
		"displayName": "Dracula Theme",
		"type": "dark",
		"import": (() => import("@shikijs/themes/dracula"))
	},
	{
		"id": "dracula-soft",
		"displayName": "Dracula Theme Soft",
		"type": "dark",
		"import": (() => import("@shikijs/themes/dracula-soft"))
	},
	{
		"id": "everforest-dark",
		"displayName": "Everforest Dark",
		"type": "dark",
		"import": (() => import("@shikijs/themes/everforest-dark"))
	},
	{
		"id": "everforest-light",
		"displayName": "Everforest Light",
		"type": "light",
		"import": (() => import("@shikijs/themes/everforest-light"))
	},
	{
		"id": "github-dark",
		"displayName": "GitHub Dark",
		"type": "dark",
		"import": (() => import("@shikijs/themes/github-dark"))
	},
	{
		"id": "github-dark-default",
		"displayName": "GitHub Dark Default",
		"type": "dark",
		"import": (() => import("@shikijs/themes/github-dark-default"))
	},
	{
		"id": "github-dark-dimmed",
		"displayName": "GitHub Dark Dimmed",
		"type": "dark",
		"import": (() => import("@shikijs/themes/github-dark-dimmed"))
	},
	{
		"id": "github-dark-high-contrast",
		"displayName": "GitHub Dark High Contrast",
		"type": "dark",
		"import": (() => import("@shikijs/themes/github-dark-high-contrast"))
	},
	{
		"id": "github-light",
		"displayName": "GitHub Light",
		"type": "light",
		"import": (() => import("@shikijs/themes/github-light"))
	},
	{
		"id": "github-light-default",
		"displayName": "GitHub Light Default",
		"type": "light",
		"import": (() => import("@shikijs/themes/github-light-default"))
	},
	{
		"id": "github-light-high-contrast",
		"displayName": "GitHub Light High Contrast",
		"type": "light",
		"import": (() => import("@shikijs/themes/github-light-high-contrast"))
	},
	{
		"id": "gruvbox-dark-hard",
		"displayName": "Gruvbox Dark Hard",
		"type": "dark",
		"import": (() => import("@shikijs/themes/gruvbox-dark-hard"))
	},
	{
		"id": "gruvbox-dark-medium",
		"displayName": "Gruvbox Dark Medium",
		"type": "dark",
		"import": (() => import("@shikijs/themes/gruvbox-dark-medium"))
	},
	{
		"id": "gruvbox-dark-soft",
		"displayName": "Gruvbox Dark Soft",
		"type": "dark",
		"import": (() => import("@shikijs/themes/gruvbox-dark-soft"))
	},
	{
		"id": "gruvbox-light-hard",
		"displayName": "Gruvbox Light Hard",
		"type": "light",
		"import": (() => import("@shikijs/themes/gruvbox-light-hard"))
	},
	{
		"id": "gruvbox-light-medium",
		"displayName": "Gruvbox Light Medium",
		"type": "light",
		"import": (() => import("@shikijs/themes/gruvbox-light-medium"))
	},
	{
		"id": "gruvbox-light-soft",
		"displayName": "Gruvbox Light Soft",
		"type": "light",
		"import": (() => import("@shikijs/themes/gruvbox-light-soft"))
	},
	{
		"id": "horizon",
		"displayName": "Horizon",
		"type": "dark",
		"import": (() => import("@shikijs/themes/horizon"))
	},
	{
		"id": "horizon-bright",
		"displayName": "Horizon Bright",
		"type": "light",
		"import": (() => import("@shikijs/themes/horizon-bright"))
	},
	{
		"id": "houston",
		"displayName": "Houston",
		"type": "dark",
		"import": (() => import("@shikijs/themes/houston"))
	},
	{
		"id": "kanagawa-dragon",
		"displayName": "Kanagawa Dragon",
		"type": "dark",
		"import": (() => import("@shikijs/themes/kanagawa-dragon"))
	},
	{
		"id": "kanagawa-lotus",
		"displayName": "Kanagawa Lotus",
		"type": "light",
		"import": (() => import("@shikijs/themes/kanagawa-lotus"))
	},
	{
		"id": "kanagawa-wave",
		"displayName": "Kanagawa Wave",
		"type": "dark",
		"import": (() => import("@shikijs/themes/kanagawa-wave"))
	},
	{
		"id": "laserwave",
		"displayName": "LaserWave",
		"type": "dark",
		"import": (() => import("@shikijs/themes/laserwave"))
	},
	{
		"id": "light-plus",
		"displayName": "Light Plus",
		"type": "light",
		"import": (() => import("@shikijs/themes/light-plus"))
	},
	{
		"id": "material-theme",
		"displayName": "Material Theme",
		"type": "dark",
		"import": (() => import("@shikijs/themes/material-theme"))
	},
	{
		"id": "material-theme-darker",
		"displayName": "Material Theme Darker",
		"type": "dark",
		"import": (() => import("@shikijs/themes/material-theme-darker"))
	},
	{
		"id": "material-theme-lighter",
		"displayName": "Material Theme Lighter",
		"type": "light",
		"import": (() => import("@shikijs/themes/material-theme-lighter"))
	},
	{
		"id": "material-theme-ocean",
		"displayName": "Material Theme Ocean",
		"type": "dark",
		"import": (() => import("@shikijs/themes/material-theme-ocean"))
	},
	{
		"id": "material-theme-palenight",
		"displayName": "Material Theme Palenight",
		"type": "dark",
		"import": (() => import("@shikijs/themes/material-theme-palenight"))
	},
	{
		"id": "min-dark",
		"displayName": "Min Dark",
		"type": "dark",
		"import": (() => import("@shikijs/themes/min-dark"))
	},
	{
		"id": "min-light",
		"displayName": "Min Light",
		"type": "light",
		"import": (() => import("@shikijs/themes/min-light"))
	},
	{
		"id": "monokai",
		"displayName": "Monokai",
		"type": "dark",
		"import": (() => import("@shikijs/themes/monokai"))
	},
	{
		"id": "night-owl",
		"displayName": "Night Owl",
		"type": "dark",
		"import": (() => import("@shikijs/themes/night-owl"))
	},
	{
		"id": "night-owl-light",
		"displayName": "Night Owl Light",
		"type": "light",
		"import": (() => import("@shikijs/themes/night-owl-light"))
	},
	{
		"id": "nord",
		"displayName": "Nord",
		"type": "dark",
		"import": (() => import("@shikijs/themes/nord"))
	},
	{
		"id": "one-dark-pro",
		"displayName": "One Dark Pro",
		"type": "dark",
		"import": (() => import("@shikijs/themes/one-dark-pro"))
	},
	{
		"id": "one-light",
		"displayName": "One Light",
		"type": "light",
		"import": (() => import("@shikijs/themes/one-light"))
	},
	{
		"id": "plastic",
		"displayName": "Plastic",
		"type": "dark",
		"import": (() => import("@shikijs/themes/plastic"))
	},
	{
		"id": "poimandres",
		"displayName": "Poimandres",
		"type": "dark",
		"import": (() => import("@shikijs/themes/poimandres"))
	},
	{
		"id": "red",
		"displayName": "Red",
		"type": "dark",
		"import": (() => import("@shikijs/themes/red"))
	},
	{
		"id": "rose-pine",
		"displayName": "Rosé Pine",
		"type": "dark",
		"import": (() => import("@shikijs/themes/rose-pine"))
	},
	{
		"id": "rose-pine-dawn",
		"displayName": "Rosé Pine Dawn",
		"type": "light",
		"import": (() => import("@shikijs/themes/rose-pine-dawn"))
	},
	{
		"id": "rose-pine-moon",
		"displayName": "Rosé Pine Moon",
		"type": "dark",
		"import": (() => import("@shikijs/themes/rose-pine-moon"))
	},
	{
		"id": "slack-dark",
		"displayName": "Slack Dark",
		"type": "dark",
		"import": (() => import("@shikijs/themes/slack-dark"))
	},
	{
		"id": "slack-ochin",
		"displayName": "Slack Ochin",
		"type": "light",
		"import": (() => import("@shikijs/themes/slack-ochin"))
	},
	{
		"id": "snazzy-light",
		"displayName": "Snazzy Light",
		"type": "light",
		"import": (() => import("@shikijs/themes/snazzy-light"))
	},
	{
		"id": "solarized-dark",
		"displayName": "Solarized Dark",
		"type": "dark",
		"import": (() => import("@shikijs/themes/solarized-dark"))
	},
	{
		"id": "solarized-light",
		"displayName": "Solarized Light",
		"type": "light",
		"import": (() => import("@shikijs/themes/solarized-light"))
	},
	{
		"id": "synthwave-84",
		"displayName": "Synthwave '84",
		"type": "dark",
		"import": (() => import("@shikijs/themes/synthwave-84"))
	},
	{
		"id": "tokyo-night",
		"displayName": "Tokyo Night",
		"type": "dark",
		"import": (() => import("@shikijs/themes/tokyo-night"))
	},
	{
		"id": "vesper",
		"displayName": "Vesper",
		"type": "dark",
		"import": (() => import("@shikijs/themes/vesper"))
	},
	{
		"id": "vitesse-black",
		"displayName": "Vitesse Black",
		"type": "dark",
		"import": (() => import("@shikijs/themes/vitesse-black"))
	},
	{
		"id": "vitesse-dark",
		"displayName": "Vitesse Dark",
		"type": "dark",
		"import": (() => import("@shikijs/themes/vitesse-dark"))
	},
	{
		"id": "vitesse-light",
		"displayName": "Vitesse Light",
		"type": "light",
		"import": (() => import("@shikijs/themes/vitesse-light"))
	}
].map((i) => [i.id, i.import]));
//#endregion
//#region node_modules/shiki/dist/engine-oniguruma.mjs
var engine_oniguruma_exports = /* @__PURE__ */ __exportAll({});
__reExport(engine_oniguruma_exports, import__shikijs_engine_oniguruma);
//#endregion
//#region node_modules/shiki/dist/bundle-full.mjs
/**
* Initiate a highlighter instance and load the specified languages and themes.
* Later it can be used synchronously to highlight code.
*
* Importing this function will bundle all languages and themes.
* @see https://shiki.style/guide/bundles#shiki-bundle-full
*
* For granular control over the bundle, check:
* @see https://shiki.style/guide/bundles#fine-grained-bundle
*/
var createHighlighter = /* @__PURE__ */ createBundledHighlighter({
	langs: bundledLanguages,
	themes: bundledThemes,
	engine: () => (0, engine_oniguruma_exports.createOnigurumaEngine)(import("./wasm_Dpm170eS.mjs"))
});
var { codeToHtml, codeToHast, codeToTokens, codeToTokensBase, codeToTokensWithThemes, getSingletonHighlighter, getLastGrammarState } = /* @__PURE__ */ createSingletonShorthands(createHighlighter, { guessEmbeddedLanguages });
//#endregion
//#region src/lib/marked.ts
/**
* Shared marked instance for the blog. Pre-renders fenced code blocks
* through Shiki via a `walkTokens` hook — each `code` token is
* rewritten to a `html` token holding Shiki's full
* `<pre class="shiki ..." style="..."><code>...</code></pre>` output.
* That keeps Shiki's theme background + token colours intact and
* sidesteps the double-`<code>`-tag wrap that `marked-highlight`
* would impose.
*
* Shiki is async, so the call site uses `await renderMarkdown(body)`.
* The highlighter is created lazily and cached for the lifetime of
* the build process.
*/
/** Languages pre-loaded into the Shiki highlighter. Anything outside
*  this list falls back to `text` (mono-spaced, no colours). Extend
*  freely — Shiki tree-shakes per build, so unused entries don't
*  bloat the runtime. */
var SUPPORTED_LANGS = [
	"ts",
	"tsx",
	"js",
	"jsx",
	"json",
	"css",
	"html",
	"astro",
	"vue",
	"php",
	"bash",
	"shell",
	"sql",
	"yaml",
	"toml",
	"ini",
	"md",
	"diff",
	"python"
];
var THEME = "github-dark-dimmed";
var highlighterPromise = null;
function getHighlighter() {
	if (highlighterPromise === null) highlighterPromise = createHighlighter({
		themes: [THEME],
		langs: [...SUPPORTED_LANGS]
	});
	return highlighterPromise;
}
var supported = new Set(SUPPORTED_LANGS);
var blogMarked = new Z({ async: true });
blogMarked.use({
	async: true,
	walkTokens: async (token) => {
		if (token.type !== "code") return;
		const lang = supported.has(token.lang ?? "") ? token.lang : "text";
		const html = (await getHighlighter()).codeToHtml(token.text, {
			lang,
			theme: THEME
		});
		token.type = "html";
		token.text = html;
	}
});
/** Render markdown to HTML with Shiki-highlighted code blocks. */
async function renderMarkdown(body) {
	return blogMarked.parse(body, { async: true });
}
//#endregion
//#region src/lib/renderBlock.ts
/**
* Build-time renderer for a single non-embed block → HTML. Text fields carry
* inline markdown (reused via `marked.parseInline`); code blocks go through the
* shared Shiki `renderMarkdown` so they match the markdown path's highlighting.
*
* Embed blocks that need a live component (`adsense`) or snippet resolution
* (`custom`) are handled by `BlockRenderer.astro`, not here — this returns "".
*/
function inline(md) {
	return f.parseInline(md ?? "", { async: false });
}
function esc(s) {
	return (s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
function youtubeId(url) {
	const m = url.match(/(?:youtu\.be\/|v=|embed\/)([\w-]{6,})/);
	return m ? m[1] : null;
}
function vimeoId(url) {
	const m = url.match(/vimeo\.com\/(?:video\/)?(\d+)/);
	return m ? m[1] : null;
}
async function renderBlockHtml(block) {
	switch (block.type) {
		case "heading": return `<h${block.level} id="${slugify(block.text)}">${inline(block.text)}</h${block.level}>`;
		case "paragraph": return block.text.trim() === "" ? "" : `<p>${inline(block.text)}</p>`;
		case "list": {
			const items = block.items.filter((i) => i.trim() !== "").map((i) => `<li>${inline(i)}</li>`).join("");
			if (items === "") return "";
			const tag = block.ordered ? "ol" : "ul";
			return `<${tag}>${items}</${tag}>`;
		}
		case "quote": return `<blockquote><p>${inline(block.text)}</p>${block.cite ? `<cite>${esc(block.cite)}</cite>` : ""}</blockquote>`;
		case "code": return renderMarkdown("```" + (block.lang || "text") + "\n" + block.code + "\n```");
		case "image": return block.url ? `<figure><img src="${esc(block.url)}" alt="${esc(block.alt)}" loading="lazy" />${block.caption ? `<figcaption>${esc(block.caption)}</figcaption>` : ""}</figure>` : "";
		case "divider": return `<hr />`;
		case "callout": return `<div class="tds-callout tds-callout--${block.variant}">${inline(block.text)}</div>`;
		case "button": return block.href ? `<p class="tds-block-button"><a class="btn btn-${block.style}" href="${esc(block.href)}">${esc(block.label || "")}</a></p>` : "";
		case "video": {
			const id = block.provider === "youtube" ? youtubeId(block.url) : vimeoId(block.url);
			if (!id) return "";
			return `<div class="tds-video-embed"><iframe src="${block.provider === "youtube" ? `https://www.youtube-nocookie.com/embed/${id}` : `https://player.vimeo.com/video/${id}`}" loading="lazy" allowfullscreen title="Video"></iframe></div>`;
		}
		default: return "";
	}
}
/**
* Render a whole block document to a single HTML string (embeds inlined as
* static markup, ads skipped). Used by the print view, which has no room for
* live ad components.
*/
async function renderBlocksToHtml(blocks, snippets = []) {
	const out = [];
	for (const block of blocks) {
		if (block.type === "adsense") continue;
		if (block.type === "custom") {
			const s = snippets.find((x) => x.id === block.snippetId);
			if (!s) continue;
			if (s.kind === "embed" && typeof s.definition.html === "string") out.push(s.definition.html);
			else if (s.kind === "preset" && typeof s.definition.type === "string") out.push(await renderBlockHtml(s.definition));
			continue;
		}
		out.push(await renderBlockHtml(block));
	}
	return out.join("\n");
}
/** Anchor id from heading text (matches sections.ts semantics). */
function slugify(text) {
	return text.toLowerCase().replace(/ä/g, "ae").replace(/ö/g, "oe").replace(/ü/g, "ue").replace(/ß/g, "ss").replace(/<[^>]+>/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 64) || "abschnitt";
}
//#endregion
//#region src/lib/translate.ts
async function call(text, to, from, html) {
	return null;
}
function translateText(text, to, from) {
	return call(text, to, from, false);
}
function translateHtml(html, to, from) {
	return call(html, to, from, true);
}
//#endregion
//#region src/lib/localizedPost.ts
/** Parse a block-document body into its blocks, or null if unparseable. */
function parseBlocks(body) {
	try {
		const doc = JSON.parse(body);
		return Array.isArray(doc.blocks) ? doc.blocks : null;
	} catch {
		return null;
	}
}
function isBlocks(post) {
	return post.bodyFormat === "blocks";
}
async function resolveLocalizedPost(slug, lang) {
	const native = await getPost(slug, lang);
	if (native) {
		const machine = native.machineTranslated === true;
		const blocks = isBlocks(native);
		return {
			post: native,
			bodyHtml: blocks ? "" : await renderMarkdown(native.body),
			blocks: blocks ? parseBlocks(native.body) : null,
			translated: machine,
			sourceLang: machine ? lang === "de" ? "en" : "de" : null
		};
	}
	const other = lang === "de" ? "en" : "de";
	const src = await getPost(slug, other);
	if (!src) return null;
	if (isBlocks(src)) {
		const [title, excerpt] = await Promise.all([translateText(src.title, lang, other), translateText(src.excerpt, lang, other)]);
		return {
			post: {
				...src,
				lang,
				title: title ?? src.title,
				excerpt: excerpt ?? src.excerpt,
				metaDescription: null
			},
			bodyHtml: "",
			blocks: parseBlocks(src.body),
			translated: title !== null,
			sourceLang: other
		};
	}
	const srcHtml = await renderMarkdown(src.body);
	const [title, excerpt, bodyHtml] = await Promise.all([
		translateText(src.title, lang, other),
		translateText(src.excerpt, lang, other),
		translateHtml(srcHtml, lang, other)
	]);
	const ok = title !== null && bodyHtml !== null;
	return {
		post: {
			...src,
			lang,
			title: title ?? src.title,
			excerpt: excerpt ?? src.excerpt
		},
		bodyHtml: bodyHtml ?? srcHtml,
		blocks: null,
		translated: ok,
		sourceLang: other
	};
}
//#endregion
export { slugify as i, renderBlockHtml as n, renderBlocksToHtml as r, resolveLocalizedPost as t };
